### PR TITLE
[ENHANCEMENT] docs: Add howto update record vectors

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

This PR adds how to update record vectors in how-to guides. Since the fields cannot be updated, the how-to guides skip them for now.

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [ ] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by davidberenstein1957 — APPROVED** [review]

**Review by davidberenstein1957 — CHANGES_REQUESTED** [review]
perhaps we can work with tabs like shown below
```python
=== "Update the metadata"
    The `metadata` of `Record` object is a python dictionary. So to update the metadata of a record, you can iterate over the records and update the metadata by key or using `metadata.update`. After that, you should update the records in the dataset.
    ```python
    updated_records = []
    for record in dataset.records():
        record.metadata["my_metadata"] = "new_value"
        record.metadata["my_new_metadata"] = "new_value"
        updated_records.append(record)
    dataset.records.log(records=updated_records)

=== "Update vectors"
       When a new vector field is added to the dataset settings, or some value for the existing record vectors must updated, you can iterate over the records and update the vectors in the same way as the metadata. 

    ```python
    updated_records = []

    for record in dataset.records():

        record.vectors["new_vector"] = [...]
        record.vector["v"] = [...]

        updated_records.append(record)

    dataset.records.log(records=updated_records)
    ```
```

**Review by davidberenstein1957 — COMMENTED** [review]
Also , the general Update records text might emphasize we are not updating fields but only question suggestions?

**Comment by frascuchon** [comment]
> Also , the general Update records text might emphasize we are not updating fields but only question suggestions?

Yes. Indeed we can update all about records but fields. I will create an issue to improve the docs about record updates. We should tackle it after the enhancement updating responses and suggestions (thanks to @burtenshaw )

**Comment by frascuchon** [comment]
> perhaps we can work with tabs like shown below
> 
> ```python
> === "Update the metadata"
>     The `metadata` of `Record` object is a python dictionary. So to update the metadata of a record, you can iterate over the records and update the metadata by key or using `metadata.update`. After that, you should update the records in the dataset.
>     ```python
>     updated_records = []
>     for record in dataset.records():
>         record.metadata["my_metadata"] = "new_value"
>         record.metadata["my_new_metadata"] = "new_value"
>         updated_records.append(record)
>     dataset.records.log(records=updated_records)
> 
> === "Update vectors"
>        When a new vector field is added to the dataset settings, or some value for the existing record vectors must updated, you can iterate over the records and update the vectors in the same way as the metadata. 
> 
>     ```python
>     updated_records = []
> 
>     for record in dataset.records():
> 
>         record.vectors["new_vector"] = [...]
>         record.vector["v"] = [...]
> 
>         updated_records.append(record)
> 
>     dataset.records.log(records=updated_records)
>     ```
> ```

Done https://argilla-io.github.io/argilla/docs_update-vectors-howto/how_to_guides/record/#__tabbed_6_1

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
