### PR TITLE
new folder and images for active learning tutorial

### PR DESCRIPTION
**Pull request by leireropl**
I added a new folder and I updated images and videos

### CODE REVIEW

**Review by dcfidalgo — COMMENTED** [review]
Thanks! Could we improve the resolution of the gif? Also, I think the png got somehow cropped, could you maybe check this?

**Comment by leireropl** [comment]
> Thanks! Could we improve the resolution of the gif? Also, I think the png got somehow cropped, could you maybe check this?

I uploaded the original .mp4 file, let me know if this works better! Also, I changed the png- path was originally wrong and I found the correct .png in another folder!

**Comment by dvsrepo** [comment]
> > Thanks! Could we improve the resolution of the gif? Also, I think the png got somehow cropped, could you maybe check this?
> 
> I uploaded the original .mp4 file, let me know if this works better! Also, I changed the png- path was originally wrong and I found the correct .png in another folder!

For GIFs I highly recommend using https://getkap.co/

**Comment by dcfidalgo** [comment]
Thanks, could you also remove the files we don't need anymore?

**Pull request merged**
