### PR TITLE
fix: broken search url

### PR DESCRIPTION
**Pull request by katsuya**
# Description

This PR fixes an issue where an invalid URL was generated due to passing an enum itself instead of its value to a template. Below are the URLs before and after the change:

- Before: `/api/datasets/dataset__07_03_2024_15_06_50/TaskType.text_classification:search`
- After: `/api/datasets/dataset__07_03_2024_15_06_50/TextClassification:search`

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by katsuya** [comment]
It seems to be due to changes in the Enum specification in 3.11. I found that it works correctly in 3.10.

- https://github.com/Eladlev/AutoPrompt/issues/47
- https://github.com/python/cpython/issues/100458

**Comment by frascuchon** [comment]
Thanks for contributing,  @katsuya 

We may have other places where this kind of error arises. I would love to know how did you find it.

**Comment by katsuya** [comment]
@frascuchon  I discovered this issue while running [autoprompt](https://github.com/Eladlev/AutoPrompt). Specifically, an error occurs at https://github.com/Eladlev/AutoPrompt/blob/7f373f219aa360cd2de38c6aa700c1dff282d7de/estimator/estimator_argilla.py#L106-L111. This section of the code checks if all records have been annotated.

**Comment by katsuya** [comment]
I checked the source code to see if this issue still occurs, and it seems to have been fixed in https://github.com/argilla-io/argilla/pull/4672. Are you still experiencing bugs even after applying this patch?

**Comment by frascuchon** [comment]
Thanks for all this info @katsuya.

**Comment by frascuchon** [comment]
> I checked the source code to see if this issue still occurs, and it seems to have been fixed in #4672. Are you still experiencing bugs even after applying this patch?

Not really, I refreshed your PR with the latest changes from develop branch and it looks is already fixed. I will close this PR, since same changes are already in develop.

**Pull request closed without merging**
