### PR TITLE
docs: retrieve user by ID

### LINKED ISSUE #5011: [DOCS] pulling user by ID does not work as specified in the docs
Hi!

thanks for this wonderful framework for text annotation. Very easy to implement and use! 

I am trying to get a user by id and it is not working as expected. The docs [here](https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#get-a-user-by-id) give the following code: 

``` python
import argilla as rg

rg.init(api_url="<ARGILLA_API_URL>", api_key="<ARGILLA_API_KEY>")

user = rg.User.from_id("00000000-0000-0000-0000-000000000000")
```

but this does not work. What does work is: 

``` python
import argilla as rg

from uuid import UUID

rg.init(api_url="<ARGILLA_API_URL>", api_key="<ARGILLA_API_KEY>")

user = rg.User.from_id(UUID("00000000-0000-0000-0000-000000000000")) ## <--- note the UUID() here


```

**Environment:**
 - Argilla Version [1.29.0]:
 - Docker Image (optional) [https://hub.docker.com/layers/argilla/argilla-quickstart/latest/images/sha256-6c33f7ce577d90cc6a1c292ff79611237da8c5e3f33d1ef7538bc05c4bc25316?context=explore]:

### PR DESCRIPTION
**Pull request by datapumpernickel**
# Description

Retrieving a user by ID works only when passing in an ID of class UUID. This has been updated in the docs, as well as in the function examples and one error message of the users.py functions. 

Closes #5011 

- [x] Documentation update

**How Has This Been Tested**

Not tested yet. 

**Checklist**

- [x] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by sdiazlor** [comment]
Thanks @datapumpernickel, could you change the branch to `main`?

**Comment by davidberenstein1957** [comment]
@datapumpernickel, would you be able to change the code so we can obtain users either by `str` or `UUID`?

**Comment by datapumpernickel** [comment]
Woopsie, I was trying to change this to the main branch and did not see your reply @davidberenstein1957 in the meantime. Sorry about the mess. 
I could look at it, probably not this week, as I will be off until Mid-July. But then I can give it a try!

**Comment by davidberenstein1957** [comment]
Hi @datapumpernickel, no problem. Your contribution is great. I think it might be nicer for users to be able to pass either an `id` or `UUID`. @frascuchon @burtenshaw WDYT? Either way, Enjoy the holidays :)

**Comment by datapumpernickel** [comment]
Definitely more convenient to be able to pass both -thanks for the hint. It actually seemed pretty straight forward, to I just put in a commit with a small change that checks if the ID is of instance uuid.UUID, if not, it tries to convert it to an instance of uuid.UUID. It returns an error if that fails for some reason.

**Comment by davidberenstein1957** [comment]
@datapumpernickel , I realised this had become stale. Sorry for that. Would you be able to resolve the merge conflict? Also, I think the `client.datasets` and `client.workspaces` have similar methods that need to be tackled.

**Comment by datapumpernickel** [comment]
Hi @davidberenstein1957, sorry, I was not able to look at this in the past weeks. I just wanted to resolve the conflicts but upon testing it again, I realised that somehow this error has been patched: 

This works now. 🎊 🚀 
```
retrieved_user = client.users(id="0d05d426-294e-4524-b391-3d8db415537c")
retrieved_user
```

All the best for the upcoming release and thanks again!

**Comment by davidberenstein1957** [comment]
@datapumpernickel, no problem. Thanks for the effort. Hope to be able to follow up a bit better with your next PR. Take care :)

**Pull request closed without merging**
