### PR TITLE
docs(#1131): Update issue templates

### LINKED ISSUE #1131: [Community] Add ISSUE templates: feature, request, bug report, etc.

### PR DESCRIPTION
**Pull request by dcfidalgo**
Closes #1131

### CODE REVIEW

**Review by dvsrepo — APPROVED** [review]
Nice! I don't know if this is the right place, but I've seen some projects where they have an option "Question" which links and takes you to the discussion

**Comment by dcfidalgo** [comment]
> Nice! I don't know if this is the right place, but I've seen some projects where they have an option "Question" which links and takes you to the discussion

You mean when you want to open an issue, there is an option (besides bug report, feature request) that says "question", and it takes you to the discussion section?

**Comment by dvsrepo** [comment]
Yes, I think that's how it worked

**Comment by dcfidalgo** [comment]
do you have an example of a project?

**Comment by dvsrepo** [comment]
I don't remember now.

Here are some examples of how to do it: https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser.

**Comment by dcfidalgo** [comment]
Got it, now there is a " Rubrix Community Support - Please ask and answer questions here." button.

**Pull request merged**
