### PR TITLE
setup and install with AWS

### PR DESCRIPTION
**Pull request by frascuchon**
This is a WIP for setup installation in AWS using docker-machine.

### CODE REVIEW

**Comment by dvsrepo** [comment]
@ignacioct can you 

(1) review this for spelling and structure
(2) convert to rst (and make sure the conversion does not introduce errors in links, headings, etc.)
(3) add this as a new section to the get started: "Setup and installation in cloud providers"

**Comment by ignacioct** [comment]
> @ignacioct can you
> 
> (1) review this for spelling and structure
> (2) convert to rst (and make sure the conversion does not introduce errors in links, headings, etc.)
> (3) add this as a new section to the get started: "Setup and installation in cloud providers"

@dvsrepo I think you ment to write this in https://github.com/recognai/rubrix/pull/192. Do you want me to move this there?

**Comment by ignacioct** [comment]
It's done. I've used https://github.com/miyakogi/m2r, which works very well in my opinion. 

I've corrected some typos, but the original structure of the .md has been preserved. Take a look at the result, and tell me if it need any change or it can be merged.

**Review by dvsrepo — APPROVED** [review]

**Comment by dvsrepo** [comment]
💯 @ignacioct

**Pull request merged**
