### PR TITLE
docs(#1092): update skweak tutorial to show new NER feature

### LINKED ISSUE #1092: [skweak] update tutorial once the NER changes are released
Just a reminder issue to update the skweak tutorial once the NER changes in the web app are released:
- use `annotation` for the gold labels when logging to Rubrix
- log the aggregated predictions instead of the predictions of each labeling function

### LINKED ISSUE #1128: [docs] Add video to skweak tutorial

### PR DESCRIPTION
**Pull request by dcfidalgo**
Closes #1092 
Closes #1128 

@frascuchon Would be nice if this could go into this week's release.

### CODE REVIEW

**Comment by dcfidalgo** [comment]
I realized I can simplify this a lot, I will push a commit as soon as possible.

**Comment by dcfidalgo** [comment]
Ok, simplified it.

I also added the correction to the install instructions with conda, now it reads:
`conda install -c conda-forge rubrix-server`

**Comment by frascuchon** [comment]
@dcfidalgo what we do with this PR finally?

**Comment by dcfidalgo** [comment]
@frascuchon I will update the screenshots/video once PR #1213 is in, and then we can merge this one.

**Comment by frascuchon** [comment]
The PR is merged now. Yo can go ahead with this

**Comment by dcfidalgo** [comment]
Ok, screenshots and video updated, feel free to merge this when you are ready.

**Review by frascuchon — APPROVED** [review]

**Pull request merged**
