### PR TITLE
New styles: Search and highlighting 

### PR DESCRIPTION
**Pull request by leiyre**
rubrix look and feel

### CODE REVIEW

**Comment by frascuchon** [comment]
@dcfidalgo could you validate this PR?

**Comment by leiyre** [comment]
fix #42

**Comment by dcfidalgo** [comment]
When i run `python -m rubrix.server` on this branch, and try to access `localhost:6900` i get this error:
```
RuntimeError: StaticFiles directory '/home/david/recognai/rubrix/src/rubrix/server/static/unsecured' does not exist.
```
Am i missing something?

**Comment by frascuchon** [comment]
> When i run `python -m rubrix.server` on this branch, and try to access `localhost:6900` i get this error:
> 
> ```
> RuntimeError: StaticFiles directory '/home/david/recognai/rubrix/src/rubrix/server/static/unsecured' does not exist.
> ```
> 
> Am i missing something?

static UI files must be built in dev mode. You ALWAYS must run `scripts/build_frontend.sh` in dev mode, or directly launch frontend app dev server (`yarn dev`)

**Comment by dcfidalgo** [comment]
Ah ok thanks! I was following our setup&installation guide, but i see now that these are only valid once we have released rubrix. Maybe we could add a dev guide to the docs explaining the setup for development. I will add this to my TODOs.

**Comment by dcfidalgo** [comment]
The search is highlighted in a light grey, but the search box is not highlighted when i activate it (write something in it). From what i understand in #42 it should be highlighted in grey, or maybe i misunderstood ... :)

**Review by dcfidalgo — COMMENTED** [review]
The search is highlighted in a light grey, but the search box is not highlighted when i activate it (write something in it). From what i understand in #42 it should be highlighted in grey, or maybe i misunderstood ... :)

**Comment by leiyre** [comment]
@dcfidalgo you are right. I explain why, I can't access easily to change the "active" behaviour. Searchbar blue background is not active state, is the browser autocomplete style so I'have reset it white

**Comment by dcfidalgo** [comment]
Ok, if this behavior is expected than feel free to merge this :+1:

**Pull request merged**
