### PR TITLE
perf(settings): deprecate index template creation environment variable

### PR DESCRIPTION
**Pull request by frascuchon**
This PR shows a log warning when environment variable `DISABLE_ES_INDEX_TEMPLATE_CREATION` is enabled, since won't be used anymore.

**NOTE: Since changes included in this PR, tests have become unstable and were failing all the time. So I've included changes in tests to fix problems. The main change is define the mocked client as fixture and inject in all related tests.**

### CODE REVIEW

**Comment by dcfidalgo** [comment]
This PR also includes some logging changes, is this wanted?

**Comment by frascuchon** [comment]
> This PR also includes some logging changes, is this wanted?

Yes, we must setup the logging configuration prior to launch a warning, in order to show early those messages with new format. That's the reason of changes.

**Review by dcfidalgo — COMMENTED** [review]
:+1: I think the `tests/test_something.py` should not be included, right?

**Comment by frascuchon** [comment]
> 👍 I think the `tests/test_something.py` should not be included, right?

Good catch!. Removed out

**Review by dcfidalgo — APPROVED** [review]

**Pull request merged**
