### PR TITLE
docs: argilla community meetup button

### PR DESCRIPTION
**Pull request by davidberenstein1957**
# Description

I updated the docs to include the community meetup within lu.ma

**Type of change**

(Remember to title the PR according to the type of change)

- [X] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [X] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [X] I added relevant documentation
- [X] I followed the style guidelines of this project
- [X] I did a self-review of my code
- [X] I made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [X] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@leiyre could you have a look here? I cannot seem to get the button in a nice and floaty way at the bottom left corner.

**Review by nataliaElv — APPROVED** [review]
Looks good! It would be good (if possible) to make the iframe big enough so that it doesn't have an internal scroll. Do you think that would be possible?

**Comment by davidberenstein1957** [comment]
Yes it would, but where do you see the internal scroll? I though I had tested this already.

**Comment by nataliaElv** [comment]
Captura de pantalla 2023-10-30 a las 17 14 01

**Comment by davidberenstein1957** [comment]
@leiyre this was already handled. I forgot about my caching 😅

**Pull request merged**
