### PR TITLE
feat: clean up trainer tests

### LINKED ISSUE #4042: [FEATURE] Clean up tests related to `ArgillaTrainer`
**Is your feature request related to a problem? Please describe.**
The tests related to the `ArgillaTrainer` could be simplified. As discussed with @davidberenstein1957 in [#3857](https://github.com/argilla-io/argilla/pull/3857#issuecomment-1759276254), the tests related to the trainer and the generation/processing of datasets have some repeated functionality that could be simplified, specially around the `formatting_func` definitions.

I can have this issue assigned with no problem.

*This PR as a [FEATURE], but please correct me if this belongs to another type.*

**Describe the solution you'd like**
Don't repeat the code in the tests, have a `helpers.py` or `conftest.py` file with common functionality.

**Describe alternatives you've considered**
Let everything as is.

**Additional context**
For example the tests in `tests/integration/client/feedback/training` or the `tests/integration/client/feedback/integrations/huggingface/test_model_card.py` have repeated `formatting_func` definitions.

### PR DESCRIPTION
**Pull request by plaguss**
# Description

This PR does some refactoring to avoid repeated code.

Closes #4042 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

Checked the tests still pass

**Checklist**

- [ ] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by davidberenstein1957 — APPROVED** [review]

**Comment by davidberenstein1957** [comment]
Looking good @plaguss. Is this ready for merging already?

**Comment by plaguss** [comment]
Yes! I wanted to take a look for other modules, but we can close this one

**Comment by davidberenstein1957** [comment]
@plaguss you can include the other modules in the PR too if you already know we are going to add some changes 💪🏽

**Comment by plaguss** [comment]
Now the formatting functions that were repeated in different modules (training and model card) are written in a `tests/integration/client/feedback/helpers.py`, I believe it's better organized this way.

**Comment by davidberenstein1957** [comment]
hi @plaguss shouldn't we add all formatting_funcs in either conftest or helpers? Now they seem split across both of them.

**Comment by plaguss** [comment]
> hi @plaguss shouldn't we add all formatting_funcs in either conftest or helpers? Now they seem split across both of them.

Do you mean the patterns used for the model card tests? I'll move those too and let only the fixtures and mocks in the `conftest.py`.

**Pull request merged**
