### PR TITLE
Documentation update: tutorial for text classification models comparison

### LINKED ISSUE #2068: feat: write tutorial about model comparison
**Is your feature request related to a problem? Please describe.**
A client asked for references about using Argilla to compare models. This might be interesting to include in a tutorial.

**Describe the solution you'd like**
2 separate datasets and compute f1 via Argilla predictions.
`inputs` param within `TextClassificationRecord` linked to 2 classes: model A vs. B

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by embonhomme**
# Description

Context: https://github.com/argilla-io/argilla/issues/2068
In this PR a new tutorial is added: model-comparison for text classification. It is the follow up of the work done during PyConFr in Bordeaux.

Closes #2068

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)
- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by embonhomme** [comment]
This PR is a WIP, because I haven't figured out how to add the notebook in docs/source/tutorials

**Comment by dvsrepo** [comment]
Hi @embonhomme this is super cool and useful!!

In order to make it even more useful, would it be possible to use SetFit's zeroshot model instead of the fewshot classy? We've just published a tutorial to show how easy is to use SetFit and many people are asking about comparisons with the zeroshot HF pipeline, so this tutorial would be awesome and make for a better comparison? https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-setfit-zeroshot.html#%F0%9F%94%AB-Zero-shot-predictions-with-SetFit

We'd be happy to walk you through if you have questions.

**Comment by embonhomme** [comment]
Hello @dvsrepo :) Thank you for the feedback, you can find in the new commit the comparaison with SetFit zero-shot. 
Tell me if it is relevant.

**Comment by dvsrepo** [comment]
This is looking just perfect!

The only one remaining change would be to review the remaining mentions of few-shot and classy-classification and replace them with zero-shot and SetFit. Then we are good to go!

We'd love to share this next week via LinkedIn and Twitter, if you'd like us to mention you as the author, send me an email to daniel @ argilla.io

**Comment by davidberenstein1957** [comment]
@embonhomme Awesome, look great to me too:)

**Comment by embonhomme** [comment]
Thank you! Yes sorry I totally forgot to change the description part. It should be better now.
Also here I have just added a Jupyter Notebook, I didn't figure out how it works with the modal.md, dvc.md,...

I will send you an email with my LinkedIn :)

**Comment by dvsrepo** [comment]
Great stuff @embonhomme!
@embonhomme, in case you can tackle this, the process is:

1. Create a folder here with the filename, like this one: https://github.com/argilla-io/argilla/tree/develop/docs/_source/_static/tutorials/training-textclassification-setfit-fewshot
2. Add the reference to the tutorial: here https://github.com/argilla-io/argilla/blob/develop/docs/_source/tutorials/libraries/setfit.md,  here: https://github.com/argilla-io/argilla/blob/develop/docs/_source/tutorials/steps/4_monitoring.md , here: https://github.com/argilla-io/argilla/blob/develop/docs/_source/tutorials/tasks/text_classification.md and here: https://github.com/argilla-io/argilla/blob/develop/docs/_source/tutorials/techniques/few_shot.md

I would say this tutorial is about Monitoring, TextClassification, few-shot

Otherwise, let us know and @davidberenstein1957 might be able to help

**Comment by embonhomme** [comment]
Thank you, I did the integration :)

**Review by davidberenstein1957 — COMMENTED** [review]
Hi, @embonhomme could you rename everything to `monitoring-textclassification-setfit-explainability`. After that, everything should be fine:) Also, did you want to participate in the LinkedIn shoutout and our community program w.r.t. offsetting? https://www.argilla.io/blog/introducing-argilla-community-growers/

**Comment by embonhomme** [comment]
Hi @davidberenstein1957 I renamed everything :)
Yes, I would like to participate in the LinkedIn shoutout!

**Comment by davidberenstein1957** [comment]
Lovely!

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
