### PR TITLE
chore: add new `FeedbackDataset` datasets in `quickstart.Dockerfile`

### LINKED ISSUE #3492: Update datasets for quickstart image
Add 2 new datasets in the quickstart docker images:

- https://huggingface.co/datasets/argilla/oasst_response_quality
- https://huggingface.co/datasets/argilla/oasst_response_comparison

Note: this may affect to the demo setup

### PR DESCRIPTION
**Pull request by alvarobartt**
# Description

This PR adds some new `FeedbackDataset` datasets in the `quickstart.Dockerfile` to be downloaded via `docker/scripts/load_data.py` when using the `"full"` value for loading datasets into Argilla as part of the quickstart.

Closes #3492

### CODE REVIEW

**Comment by alvarobartt** [comment]
@gabrielmbmb at #3492, @frascuchon mentioned that changing the `FeedbackDataset` datasets that were downloaded as part of the `quickstart.Dockerfile` may affect the demo setup, could you please check?

I've also included those when using the `"full"` arg, so `"simple"` will still just download `argilla/databricks-dolly-15k-curated-en`

**Review by gabrielmbmb — APPROVED** [review]

**Comment by gabrielmbmb** [comment]
hey @alvarobartt, the demo instance won't be affected by this change! it has a different setup :)

**Comment by nataliaElv** [comment]
Is it too difficult to point this PR to main instead of the release? Just so that we can have it available ASAP and not being dependent on the release. Thanks!

**Comment by alvarobartt** [comment]
Hi @nataliaElv, yes :( that's an issue since the original branch was created on top of `releases/1.14.0` instead of `main`, so we cannot just change the base, I can either create a new PR or just merge main, rebase the commits and force push just the changes related to `load_data.py`. Anyway, what's your idea on using it? You can use it from this branch already, and, alternatively, we could just push it to the Docker Hub manually if that helps?

**Comment by nataliaElv** [comment]
> Hi @nataliaElv, yes :( that's an issue since the original branch was created on top of `releases/1.14.0` instead of `main`, so we cannot just change the base, I can either create a new PR or just merge main, rebase the commits and force push just the changes related to `load_data.py`. Anyway, what's your idea on using it? You can use it from this branch already, and, alternatively, we could just push it to the Docker Hub manually if that helps?

In this case I would suggest to close this PR without merging and creating a new PR that points to `main`. Please check that `argilla/oasst_response_quality` gets loaded correctly (it's giving me issues when trying to load it in a notebook).

**Comment by alvarobartt** [comment]
> In this case I would suggest to close this PR without merging and creating a new PR that points to `main`. Please check that `argilla/oasst_response_quality` gets loaded correctly (it's giving me issues when trying to load it in a notebook).

Hi @nataliaElv the issue that you mention is already solved at #3539, and regarding the PR, we cannot point to `main` as it won't work since it's relying on the fix created on top of `releases/1.14.0`, but we can guide you on how to build and run it locally if that works!

**Pull request merged**
