### PR TITLE
docs: popular issues file generator

### LINKED ISSUE #4967: [DOCS] Popular issues file generator
## Which page or section is this issue related to?

Related to this [PR](https://github.com/argilla-io/argilla-python/pull/73)

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

Script to automatically retrieve the github issues and generate a doc with the most popular.

NOTE: By the moment, I left it commented in mkdocs.yml as I don't know if this will be added for 2.0. So, when merged, it's saved but not run. Using it, the docs building takes around 20 seconds more.

TO BE DISCUSSED (below a screenshot):

1. Still not sure about the given names to each table, probably it's better to shorten them.
2. I added it to Community, but if you think this is more suitable in other section, we can discuss it.
3. I ran it locally, but I don't know if any external workflow must be also updated.
4. Any other feedback is welcome!

screencapture-127-0-0-1-8000-argilla-python-community-popular-issues-2024-06-06-14_32_12

Closes #4967 

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

- [x] Run with `mkdocs serve`

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@sdiazlor looking great! Amazing.

I think "popular issues" does not fully cover "planned issues for upcoming release", perhaps we can change the naming to something like "issue dashboard" or something?

Additionally, would you be able to do something similar but minimal for the changelog too?

**Comment by nataliaElv** [comment]
Looks super cool! Will it be automated somehow or do we need to regenerate the file from time to time?

**Comment by sdiazlor** [comment]
> Looks super cool! Will it be automated somehow or do we need to regenerate the file from time to time?

@nataliaElv Great! With this, the file will be created automatically after each publication, that is, after each release :)

**Comment by nataliaElv** [comment]
That sounds great! 😃 Thanks for taking care of this one.

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
