### PR TITLE
bugfixes: change ARGLLA_API_KEY to rubrix.apikey

### LINKED ISSUE #2074: ARGILLA_API_KEY is different in documentation and codebase
## Description
In the [python client](https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.init) and [user management](https://docs.argilla.io/en/latest/getting_started/installation/user_management.html#default-user) document section, `api_key` is different in documentation and codebase. Please find the screenshot of the documentation and codebase for reference. This needs to be updated to `argilla.apikey`, but this also needs to be backward compatible with older versions.

## Screenshots
1. [Codebase](https://github.com/argilla-io/argilla/blob/develop/src/argilla/_constants.py#L21)
image

2. Python Client section

image

3. User Management section

image

## Environment
 - OS: MacOS
 - Browser: Chrome
 - Argilla Version:
 - ElasticSearch Version: 7.10.2
 - Docker Image: argilla/argilla-server:pr-2057

### PR DESCRIPTION
**Pull request by rhoitjadhav**
# Description
Change default ARGILLA_API_KEY to `rubrix.apikey`

Closes #2074 

**Type of change**

- [x] Bug fixes

**How Has This Been Tested**

Tested locally on docker

**Checklist**

- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by frascuchon** [comment]
We should update also the docs referring to the quickstart server setup https://github.com/argilla-io/argilla/issues/2074#issuecomment-1405026657, right?

**Comment by rhoitjadhav** [comment]
Thanks for pointing out. I have updated the `quickstart.README.md` file specifying the default API Keys. I think that's the only change on the docs side.

**Comment by dvsrepo** [comment]
> Thanks for pointing out. I have updated the `quickstart.README.md` file specifying the default API Keys. I think that's the only change on the docs side.

Yes, on my side I think it's the only place we need to change that, as we are keeping rubrix.apikey for now.

**Comment by rhoitjadhav** [comment]
@dvsrepo We also need to specify default api key in the HF docs as the raw doc you gave me on [slack](https://argilla-team.slack.com/archives/D04DSV54FHA/p1674465998625309) does not contains the default api key. Please correct me if any

**Comment by dvsrepo** [comment]
> @dvsrepo We also need to specify default api key in the HF docs as the raw doc you gave me on [slack](https://argilla-team.slack.com/archives/D04DSV54FHA/p1674465998625309) does not contains the default api key. Please correct me if any

Thanks for pointing this out, I'll review but I intentionally left this out, and now that is `rubrix.apikey` I see even less interest in adding it. Also we don't have as much control over updating that guide so I prefer to keep it simple. Revisiting the tutorials for Colab what I've found relevant and clearer is to indicate the team.apikey so I might revise that.

Thanks!

**Review by frascuchon — APPROVED** [review]

**Pull request merged**
