### PR TITLE
feat(#1355) Improve table actions and styles

### LINKED ISSUE #1333: [UI] Rules table by screen size
table rules:

Large screen : 
divtable-info : 130 px para todos except "Query" that we'll be longer

Small (1024):
Option to discuss with @leiyre 

- Rework some title column name ("Cov." "Annot. cov." "Incorr.")?
- Force sort icon on next line? and avoid 3 lines

### LINKED ISSUE #1355: [Datasets] Improve table actions
- Include all filters as part of query url
- Allow filter by tags

See #1303  #1333 #705

### PR DESCRIPTION
**Pull request by leiyre**
closes #1355
closes #1333

This PR allows filter by tags, includes all filters as part of query url and improves some styles

### CODE REVIEW

**Comment by frascuchon** [comment]
The original issue #1355 refers to issues #1303 and #1333.

Are resolved too? In that case, could you please include the reference in the PR description?

cc @leiyre

**Comment by leiyre** [comment]
@frascuchon #1303 is not compatible with filter by tags

**Comment by frascuchon** [comment]
- [x] With filters applied, clicking the **Datasets** breadcrumb restores the query URL but filters remain active.
Screenshot 2022-04-07 at 10 17 59

- [x] Textual search does not work with tag filter
Screenshot 2022-04-07 at 10 21 16

- [x] Applied tags sometimes do not keep active
Screenshot 2022-04-07 at 10 23 05

**Review by frascuchon — APPROVED** [review]
+1

**Pull request merged**
