### PR TITLE
docs: Update links to Argilla HF Spaces in documentation

### LINKED ISSUE #4193: [DOCS] Update button Deploy on HF Spaces url
## Which page or section is this issue related to?

It seems HF has changed the query param for creating new spaces, so our button Deploy on HF Spaces doesn't work.
Now is https://huggingface.co/new-space?template=Argilla

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #4193 
**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by sdiazlor** [comment]
@ignacioct I have quickly updated the URLs, so could you please check if they are correct? Also, in the huggingface-spaces.md file (or any other similar file), could you check if the explanation needs improvement or if the image requires an update?

**Comment by davidberenstein1957** [comment]
@sdiazlor , I believe the URL should be? https://huggingface.co/new-space?template=argilla%2Fargilla-template-space
https://huggingface.co/new-space?template=Argilla/argilla-template-space does not seem to work for me

**Comment by ignacioct** [comment]
> @sdiazlor , I believe the URL should be? https://huggingface.co/new-space?template=argilla%2Fargilla-template-space https://huggingface.co/new-space?template=Argilla/argilla-template-space does not seem to work for me

@davidberenstein1957 the links that Sara pushed are working for me though. They are [https://huggingface.co/new-space?template=Argilla](https://huggingface.co/new-space?template=Argilla)

**Comment by davidberenstein1957** [comment]
closing this because it was handled from the side of HF @sdiazlor @ignacioct

**Comment by sdiazlor** [comment]
@davidberenstein1957 nevertheless in this PR, as you mentioned in the issue, I also commited the reference to private HF Spaces, should I create a new PR for that?

**Comment by davidberenstein1957** [comment]
@sdiazlor, good catch! Could you create a separate PR for that?

**Comment by davidberenstein1957** [comment]
@ignacioct, could you also add this private space usage reference to the publication ideas as a post?

**Comment by ignacioct** [comment]
> @ignacioct, could you also add this private space usage reference to the publication ideas as a post?

Like a tutorial on how to use private spaces with Argilla? I think Dani talked about it in a community meeting you sent me

**Comment by davidberenstein1957** [comment]
@ignacioct, correct. The idea could be just showing a brief code snippet.

**Comment by sdiazlor** [comment]
> @sdiazlor, good catch! Could you create a separate PR for that?

yes, no problem

**Pull request closed without merging**
