### PR TITLE
docs: add fastfit tutorial

### LINKED ISSUE #4878: [DOCS] Add FastFit tutorial

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

A new tutorial using FastFit. I also added how to calculate annotation performance with some of the most known metrics to give more value, and as I saw that only Kripendorff's alpha is currently available in Argilla.

Closes #4878

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by davidberenstein1957 — COMMENTED** [review]
Hi, @sdiazlor, it is looking good. I think we might miss a part of the charm of `fast-fit` by only using 5 examples per class. I saw this cool blogpost a week back showcasing fastfit vs setfit, perhaps you can add something similar and reference the author? You can find it when Googling ("setfit vs fastfit"). perhaps we can mention something in the text mentioning training is much quicker but inference is slower?
image

**Comment by davidberenstein1957** [comment]
Also, I believe we can just use fastfit like this?

```
from fastfit import FastFit
from transformers import AutoTokenizer, pipeline

model = FastFit.from_pretrained("fast-fit")
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")
classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)

print(classifier("I love this package!"))
````
Similarly, there are some warning etc underneath certain code blocks.

**Comment by sdiazlor** [comment]
> Also, I believe we can just use fastfit like this?
> 
> ```
> from fastfit import FastFit
> from transformers import AutoTokenizer, pipeline
> 
> model = FastFit.from_pretrained("fast-fit")
> tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")
> classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)
> 
> print(classifier("I love this package!"))
> ```
> 
> Similarly, there are some warning etc underneath certain code blocks.

Yes, however, if using a base BERT model, it doesn't work the inference, that's the reason why. I wanted to include it, in case, someone changed it and found an error. But maybe it's better to do it the other way around, use a ROBERTA base model and just add it as a note.

**Comment by ignacioct** [comment]
Hi! A couple of things:

- [ ] In the import `from argilla.feedback import ArgillaTrainer, FeedbackDataset, TrainingTaskMapping`, `FeedbackDataset` is not used.
- [ ]  Wouldn't it be better to do all the imports at the beginning? Maybe kind of a debate but I usually prefer getting rid of all the imports, as I think you win in readability in the body of the tutorial.
- [ ] In the pandas DataFrame that is shown at the end, I will add a few columns, showing which is the label with the highest probability, i.e., the one that is predicted. You really dunno which label is being predicted.

**Review by ignacioct — CHANGES_REQUESTED** [review]
Hi! A couple of things:

- [ ] In the import `from argilla.feedback import ArgillaTrainer, FeedbackDataset, TrainingTaskMapping`, `FeedbackDataset` is not used.
- [ ]  Wouldn't it be better to do all the imports at the beginning? Maybe kind of a debate but I usually prefer getting rid of all the imports, as I think you win in readability in the body of the tutorial.
- [ ] In the pandas DataFrame that is shown at the end, I will add a few columns, showing which is the label with the highest probability, i.e., the one that is predicted. You really dunno which label is being predicted.

**Comment by sdiazlor** [comment]
> Hi! A couple of things:
> 
> * [ ]  In the import `from argilla.feedback import ArgillaTrainer, FeedbackDataset, TrainingTaskMapping`, `FeedbackDataset` is not used.
> * [ ]   Wouldn't it be better to do all the imports at the beginning? Maybe kind of a debate but I usually prefer getting rid of all the imports, as I think you win in readability in the body of the tutorial.
> * [ ]  In the pandas DataFrame that is shown at the end, I will add a few columns, showing which is the label with the highest probability, i.e., the one that is predicted. You really dunno which label is being predicted.

@ignacioct Sorry, I believe you reviewed the wrong tutorial 😅

**Review by ignacioct — APPROVED** [review]
Ups! Sorry for the prior mistake. Picked a tutorial that was almost the same name, my bad! Here's an updated set of suggestions, but everything looks really nice rn:

- [x] Maybe set the random seed to a fixed value for controlling the sampling.
- [x] Maybe a paragraph analysing each of the annotations metrics? Specially useful for the confusion matrix, as there's a row that seems to be showing a rather odd behaviour. I would include a short sentence at the end of each annotation metric sections summarizing what the metric results mean.
- [x] And also maybe getting these insights into the conclusions to make it a bit bigger.

**Pull request closed without merging**
