### PR TITLE
Add text2text example: text summarisation

### LINKED ISSUE #419: Add text2text example (e.g., text summarisation)
Add the text summarisation fine-tuning tutorial similar to sentiment classifier fine-tuning tutorial:

https://rubrix.readthedocs.io/en/stable/tutorials/06-labeling-finetuning.html#3.-Fine-tune-the-pre-trained-mode

### PR DESCRIPTION
**Pull request by krishnajalan**
Closes #419

### CODE REVIEW

**Comment by dvsrepo** [comment]
@davidberenstein1957 could review this PR and see where it fits in the upcoming docs?

**Comment by davidberenstein1957** [comment]
@krishnajalan Thanks for your contribution💪🏽! We are currently restructuring the docs but I will make sure to take a look later this week.

**Comment by davidberenstein1957** [comment]
LFTM @frascuchon could merge the PR? I don't have access still.

**Comment by davidberenstein1957** [comment]
I added this manually to easy the merge with the new doc set-up.

**Comment by davidberenstein1957** [comment]
@krishnajalan https://docs.argilla.io/en/latest/guides/tasks/text_generation.html#Text-Summarization Thanks a lot! ❤️

**Pull request closed without merging**
