### PR TITLE
refactor: Change the default api key to `argilla.apikey`

### LINKED ISSUE #2250: Update API key for default user to `argilla.apikey`
- The default API KEY will be defined as `argilla.apikey`
- The old API KEY will be accepted when default API KEY is not changed
- Docs must be updated to point this new API KEY value. And also, warning about new clients connecting to old servers. For example: 

>To connect to an old Argilla server using client `>=1.3.0`, you should specify the default user API key `rubrix.apikey`. Otherwise, connections will fail with an Unauthorized server error.

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

This PR adds code to change the default API key to `argilla.apikey`, with backward compatibility with old apikey.

Closes #2250 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Refactor (change restructuring the codebase without changing functionality)
- [x] Documentation update

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] I added comments to my code
- [x] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by frascuchon** [comment]
@rhoitjadhav 
Could you update the docs with this new default value? Also, add a disclaimer/info/warn for old server connections as suggested in the issue.

**Comment by rhoitjadhav** [comment]
@frascuchon I have to make the changes In the same PR branch right?

**Comment by frascuchon** [comment]
> @frascuchon I have to make the changes In the same PR branch right?

Yes, you can add your changes here.

**Comment by rhoitjadhav** [comment]
Updated the docs with new default api key

**Pull request merged**
