### PR TITLE
New feature: Fine-Tuning BERT for NER Notebook

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

We have added a new notebook with a tutorial on how to visualize a dataset with Argilla and use it to fine-tune a BERT for NER. This tutorial is prepared for beginners who wish to have a first approach in a simple way. 

**Type of change**

- New feature (non-breaking change which adds functionality)
- Documentation update

**How Has This Been Tested**

This Notebook was tested using Google Colab.

**Checklist**

- [x] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, I've returned from holidays. Have you been able to make any progress on this based on my comments?

**Comment by sdiazlor** [comment]
Hi @davidberenstein1957, I have updated the notebook to remove the O-tokens when visualizing in Argilla. Please, let me know your thoughts.

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, Thank you! I will have a look later today.

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, the tutorial looks great already, however, there is another small caveat. Normally, we span BIOU annotations over multi-word annotation. For example, "2nd day of 2015" is now visualized as individual annotations? B-TIME (begin) I-TIME (inside) and O-TIME (outside), we want to annotate it as a single Span (set of words) with the label TIME.

**Comment by sdiazlor** [comment]
Hi @davidberenstein1957, okay, I'll check it, so it can be improved.

**Comment by sdiazlor** [comment]
Hi @davidberenstein1957, it should work now with the changes I made.

**Comment by davidberenstein1957** [comment]
Awesome @sdiazlor, this looks great. Looking forward to getting started in the coming weeks

**Pull request merged**
