### PR TITLE
︷ Custom field with handlebars

### PR DESCRIPTION
**Pull request by damianpumar**

### CODE REVIEW

**Comment by burtenshaw** [comment]
@damianpumar should we review and merge this?

**Comment by damianpumar** [comment]
> @damianpumar should we review and merge this?

Yes, we can, but I need to change the "mode"

**Comment by damianpumar** [comment]
@burtenshaw could you share with me how can I detect the advanced or basic mode?
Just to apply this little change and merge this PR.

Thanks!

**Comment by burtenshaw** [comment]
> @burtenshaw could you share with me how can I detect the advanced or basic mode? Just to apply this little change and merge this PR.
> 
> Thanks!

Hey @damianpumar , the `/datasets/{id}/fields` endpoint will give this response for custom fields:

```json
{
"id": "51e8fb70-3c3a-4b19-8919-906b28d5c2fd",
"name": "custom",
"title": "custom",
"required": true,
"settings": {
  "type": "custom",
  "template": "<div>{{field}}</div>",
  "advanced_mode": false
},
"dataset_id": "5d9483e5-6f66-4fd6-b56c-54399002f54d",
"inserted_at": "2024-09-26T08:23:42.148948",
"updated_at": "2024-09-26T08:23:42.148948"
}
```

So you can use `advanced_mode` as a bool.

**Comment by damianpumar** [comment]
@burtenshaw Thanks!
Now we can merge it, feel free to merge it when you want!

**Pull request merged**
