### PR TITLE
accept flat text as input for token classification mapper

### PR DESCRIPTION
**Pull request by Ankush-Chander**
Please refer: #482

### CODE REVIEW

**Comment by Ankush-Chander** [comment]
Hi @frascuchon 
Hope you are safe and doing well!
 
Is there a way I can test these changes?

**Comment by frascuchon** [comment]
Hi @Ankush-Chander 

Great the quick work.

You can do some tests following [the monitor tutorial](https://rubrix.readthedocs.io/en/stable/tutorials/09-automatic_fastapi_log.html)

Basically, you can configure a FastAPI application as follows:

```python
app = FastAPI()

app.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/predict", # or "/predict/ need to check"
    dataset="monitoring_spacy",
)

# prediction endpoint using spacy pipeline
@app.post("/predict")
def predict_spacy(batch: List[str]):
    predictions = []
    for text in batch:
        doc = spacy_pipeline(text)  # spaCy Doc creation
        # Entity annotations
        entities = [
            {"label": ent.label_, "start": ent.start_char, "end": ent.end_char}
            for ent in doc.ents
        ]

        prediction = {
            "text": text,
            "entities": entities,
        }
        predictions.append(prediction)
    return predictions
```

**Comment by frascuchon** [comment]
Hi, @Ankush-Chander I hope you're well.

I found a way to include a minimal check of this change to adapt the current test on [`test_asgi.py`](https://github.com/Ankush-Chander/rubrix/blob/issue_482/tests/client/test_asgi.py#L126) including the following piece of code:

```python
mock.post(
        expected_endpoint,
        json=[{"text": "The main text data"}, "The main text data"],
    )
```

The main change is that the JSON input includes a raw text string.


Also, I've included some changes to allow running tests from a collaborator branch. So, please, rebase/merge your branch from master.

Let me know if you can afford the changes. 

Thanks!

**Review by frascuchon — APPROVED** [review]
Great !!!!!!

**Pull request merged**
