### PR TITLE
Docs: Adds tutorial about custom few-shot classification with SetFit

### LINKED ISSUE #1741: Docs: Add new tutorial using SetFit, few-shot classification package

### PR DESCRIPTION
**Pull request by dvsrepo**
Closes #1741

### CODE REVIEW

**Comment by dvsrepo** [comment]
closes #1741

**Review by frascuchon — APPROVED** [review]

**Comment by frascuchon** [comment]
Do you need some extra info to merge this @dvsrepo?

**Comment by dvsrepo** [comment]
> Do you need some extra info to merge this @dvsrepo?

No, can you merge this?

**Comment by frascuchon** [comment]
DOne !

**Pull request merged**
