### PR TITLE
feat(#1063): Token Classifier fine tuning content selection

### LINKED ISSUE #1052: [NER Label selector ] Update style
- [ ] Improve label list view
- [ ] Improve interaction

### LINKED ISSUE #1063: [NER Fine tuning] content selection
### Multi word

Actual state : (VIEW SS)
1- I select various words, highlight is grey and in a solid block (Highlight/words).
2- When selection is done, highlight selection is splited and label selector appears.

- [x] Should be:

1- I select various words, highlight is grey and splited (highlight/word)
2- When selection is done, highlight selection is a solid block label selector appears.

### Delete labelling

- [x] Make clicable the whole tooltip to delete

### Selection on a searched word

- [x] Selection highlight should not be cut (SS)
- [x] When selection is containing a search word the label selector does not appear (how it works only on right>left sense)
- [x] In general : change appearance of results : in place of Orange highlight show text in *bold*

### Cursor 

- [x] Active "hand" cursor (pointer) on piece of text already annotated/Predicted
- [x] Active "Text Select" cursor on the rest of record
- [x] Enlarge the hover state to the whole area : (record + annotated tooltip + empty space between them) (record + predicted tooltip + empty space between us)

### New Select label modal

- [x] Integrate new UI modal
- [x] In case of unique label, dont show modal, and just affect label after selecting text
- [x] Add logic to show first and preselected the last label used
- [x] Add following Keyboard shortcut: Enter to valid preselected label, and vertical arrow keyboard or Number to valid other labels

### LINKED ISSUE #1074: [NER visualization] Text in records appears duplicated
The more annotated, the bigger is text duplication

See image:
Screenshot 2022-02-01 at 16 26 59

### PR DESCRIPTION
**Pull request by leiyre**
This PR adds new UI, improves content selection in Token Classifier, improves styles and shortcut for annotation

Closes #1063
Closes #1074
Closes #1052

### CODE REVIEW

**Comment by frascuchon** [comment]
Will close also #1074, @leiyre ?

**Comment by frascuchon** [comment]
And what about this one #1052 ?

**Comment by leiyre** [comment]
@frascuchon yes, thisPR closes both

**Review by frascuchon — APPROVED** [review]
Pending feedback

**Pull request merged**
