### PR TITLE
Refactor/remove no workspace usage and better superuser computation

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

For old argilla versions, workspaces were not required to create datasets. Some code changes were included to support this behavior 

This PR clean these code sections and refactor them for those code parts where old logic was used. For example, the `user.is_superuser` flag is computed from the workspace list setup but also persisted to improve the code usability.

We need still to provide a way to migrate those datasets that have no dataset to a default workspace. @davidberenstein1957 can you provide a section in docs where to include these steps from the release notes?

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (change restructuring the codebase without changing functionality)
- [ ] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] I added comments to my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/latest/getting_started/installation/configurations/elasticsearch.html#reindex-data

https://docs.argilla.io/en/latest/guides/log_load_and_prepare_data.html#Reindex-a-Dataset

I think they can be added here.

**Comment by frascuchon** [comment]
Thanks,  @davidberenstein1957 

Indeed, it's an elasticsarch index update for the index of datasets (which contains all datasets' meta info). 

So, I was thinking of something like:

> If you have datasets with empty workspaces (-), please launch this python script before installing this upgrade,...balbalbla)

Maybe we can just include it in the CHANGELOG section?

**Comment by frascuchon** [comment]
@davidberenstein1957 Let me prepare a migration flow draft and let's start discussing it.

**Comment by frascuchon** [comment]
@davidberenstein1957 PR #2382 includes the migration section affecting this.

Please, take a look at the docs and give your feedback, pls. https://docs.argilla.io/en/docs-add-section-for-empty-workspace-migration/guides/log_load_and_prepare_data.html?highlight=load%20and%20prepare#Migrating-dataset-from-%E2%80%9Cemtpy%E2%80%9D-workspaces

**Review by jfcalvo — APPROVED** [review]

**Pull request merged**
