### PR TITLE
Including some info about the upgrade and migration

### PR DESCRIPTION
**Pull request by frascuchon**

### CODE REVIEW

**Review by dvsrepo — CHANGES_REQUESTED** [review]
I've reviewed this. 

The only change to make is to include the link in the readme's menu to the md in `docs`, what would be the best link until we merge this into main?

**Comment by frascuchon** [comment]
> I've reviewed this.
> 
> The only change to make is to include the link in the readme's menu to the md in `docs`, what would be the best link until we merge this into main?

The README doc is included in the pypi Argilla page. Could we share from here?

**Comment by frascuchon** [comment]
I've already setup the relative link. 

Take a look [here](https://github.com/recognai/rubrix/tree/docs/add-a-migration-guide-in-readme#) @dvsrepo

**Review by dvsrepo — APPROVED** [review]

**Comment by dvsrepo** [comment]
This could be merged @frascuchon

**Pull request merged**
