### PR TITLE
[DOCS] Added information about tests in developer documentation

### LINKED ISSUE #3143: [DOCS] add additional dev/contributor documentation about running tests
## Which page or section is this issue related to?
There is no clear instruction on running tests.

N.A.

### PR DESCRIPTION
**Pull request by hjain5164**
# Description

Added the information on how to execute the tests in the developer documentation.

Closes #3143 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

- [x] By executing `make html` and tested the markdown content.

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Hi @hjain5164, it looks great already but I believe we actually need to run ElasticSearch and then run the Argilla server via `python -m argilla` to run the tests. Could you represent this more explicitly in your PR? Also, it would be great if you could add some additional references to the importance of running tests within [the contributor documentation](https://docs.argilla.io/en/latest/community/contributing.html).

**Comment by hjain5164** [comment]
Yes, you are right. Also, what I feel is let's have the information about tests after the [Running Argilla server](https://docs.argilla.io/en/latest/community/developer_docs.html#running-argilla-server) as I think that should make more sense because without setting up everything tests may not work properly. So, let me change the positioning of this information and then adding the info about argilla server may not be required, right? 

Although, I will have to add steps to start elasticsearch anyways. Will add reference to contributor docs as well :)

**Comment by davidberenstein1957** [comment]
Hi @hjain5164, yes for me it makes sense to add the references about the tests after running the Argilla server. Good catch! Looking forward to the rest of the PR 💪🏽

**Comment by frascuchon** [comment]
> Hi @hjain5164, yes for me it makes sense to add the references about the tests after running the Argilla server. Good catch! Looking forward to the rest of the PR 💪🏽

Sorry for the late response here, but you don't need to run a local Argilla server. The tests are using a wrapped [Starlette TestClient](https://www.starlette.io/testclient/) to avoid this requirement. The only thing you need is a running elasticsearch instance running. Then you can launch the whole test suite:
```bash
pytest test
```

**Review by davidberenstein1957 — APPROVED** [review]

**Comment by davidberenstein1957** [comment]
Hi @hjain5164, merging this for now. Do you still want to work on the other comments from @frascuchon and handle them in a separate PR and issue?

**Pull request merged**
