### PR TITLE
Snorkel tutorial update

### PR DESCRIPTION
**Pull request by javispp**

### CODE REVIEW

**Comment by ignacioct** [comment]
Is this PR only for the snorkel tuto? Because I'm seeing changes on Docker files and dev files, maybe we should proceed with care.

**Comment by javispp** [comment]
The tutorial is ready for review. I'm having too many issues with the Windows Subsystem for Linux and it's doing weird stuff with the files sometimes. I'll check it.

**Comment by dvsrepo** [comment]
Thanks a lot Javier! I will do a quick review next week and we can merge it.

**Comment by dvsrepo** [comment]
we'll close this one, and merge the PR with the reviewed version

**Pull request closed without merging**
