### PR TITLE
fix: 'WeakMultiLabels.summary' and 'show_records' after extending the weak label matrix

### LINKED ISSUE #1631: [WeakMultiLabels] The 'summary' does not take into account the extended matrix.
**Describe the bug**
After extending the weak label matrix via `WeakMultiLabels.extend_matrix()`, the `summary` and `show_records` methods do not consider the extended matrix. 

**To Reproduce**
1. Extend a weak label matrix via `WeakMultiLabels.extend_matrix()` with 0 thresholds.
2. Compare the `WeakMultiLabels.summary()` before and after extending the matrix.

**Expected behavior**
The `summary` and `show_records` methods should consider the extended matrix.

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Rubrix Version [e.g. 0.10.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

### PR DESCRIPTION
**Pull request by dcfidalgo**
Closes #1631

### CODE REVIEW

**Review by frascuchon — APPROVED** [review]
Great!

I let a bit piece of the clean code bible  about naming:

> Other than that, when you naming classes, use nouns and adjectives like Customer, Product, and Student, etc. If it is a function or method, use verbs like getName, getTotalCount, setProductName and addCustomerName etc.

When I see `matrix` or `summary` I think about property more than an action. Maybe now I'm an old and obsolete guy :-(

**Review by frascuchon — CHANGES_REQUESTED** [review]
Sorry, just a thing that I forgot. Please, create the PR against the releases branch for bugfixes.

**Comment by dcfidalgo** [comment]
Yes, the naming is probably not optimal. Maybe `get_matrix()` and `compute_summary()` would be better, I leave these improvements for you, old man :older_man: :)

Ok, will rebase this PR on the release branch and change the target branch.

**Review by frascuchon — APPROVED** [review]
👍

**Pull request merged**
