### PR TITLE
[CONFIG] `argilla`:  Add Python 3.13 support

### LINKED ISSUE #5627: [FEATURE] Add Python 3.13 support
**Is your feature request related to a problem? Please describe.**

Hello, I'd like to upgrade my app to python 3.13 but I can't due to argilla not supporting 3.13. What's the roadmap and timeline for this ?

**Describe the solution you'd like**

Argilla supports 3.13

**Describe alternatives you've considered**

Removing argilla from my app

**Additional context**

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

Closes https://github.com/argilla-io/argilla/issues/5627

**Type of change**

- Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by frascuchon** [comment]
Problems using python 3.13 + pyarrow https://github.com/apache/arrow/issues/44443

**Comment by oulianov** [comment]
The dependencies install pyarrow 17.0.0, but python 3.13 is only supported for pyarrow 18.0.0 (released 2 days ago)
https://github.com/apache/arrow/issues/43519

**Comment by oulianov** [comment]
I ran `pdm lock` with the latest `pdm` version using your `pyproject.toml` file. The solver gave me the right version of pyarrow (18.0). 

Capture d’écran 2024-10-30 à 17 33 18

So my guess is you just need to run `pdm lock` again and tests will pass for 3.13 :) 

Let me know how it goes.

**Comment by frascuchon** [comment]
Thanks for the tip @oulianov. The `pdm lock` will update other dependencies making the whole [workflow fails](https://github.com/argilla-io/argilla/actions/runs/11601885741).

I defined the 18.0.0 as a dev dependency and [everything is working](https://github.com/argilla-io/argilla/pull/5652/commits/8f6a173fa9efd13e54e2746b35ef2685769c4e03).  

@burtenshaw I think this is ready to merge.

**Review by burtenshaw — APPROVED** [review]
Looks good. Let's merge it.

**Pull request merged**
