### PR TITLE
feat(#1432): configure dataset settings

### LINKED ISSUE #1432: [Datasets] Allow configuring datasets with a predefined label schema
The idea here is to create datasets with a labels schema.

With this new feature, users can create or update datasets with a set of labels to simplify the annotation process.

### PR DESCRIPTION
**Pull request by frascuchon**
Following the work to resolve issue #1432, this PR includes client functions to configure dataset settings passing the labels schema.

```python
import rubrix as rb

rb.configure_dataset(name="my-ds", settings=rb.TextClassificationSettings(labels_schema=["A", "B","C"]))
```

This PR must be merged after #1471

### CODE REVIEW

**Comment by frascuchon** [comment]
@dcfidalgo It would be nice if you write some documentation about this new feature. This could help with the PR review.

**Comment by dcfidalgo** [comment]
@frascuchon `labels_schema` sounds strange to me, I would vote for either `labeling_schema` or `label_schema`.

**Comment by frascuchon** [comment]
In that case, I prefer `label_schema`. Also server part should be updated

**Comment by dcfidalgo** [comment]
Ok, let's get this PR in and make the name change in another PR

**Comment by frascuchon** [comment]
> Ok, let's get this PR in and make the name change in another PR

You can review this PR #1486

**Review by dcfidalgo — APPROVED** [review]

**Pull request merged**
