### PR TITLE
feat: add German translation

### PR DESCRIPTION
**Pull request by paulbauriegel**
# Add German translation

I added a i18n translation file for German, because we want to use Argilla in a setting where people only speak that language. Let me know if that would work like that.

**Type of change**

- [x] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

I only added the i18n translation for German, and checked that the UI works based on the browser setting. Please let me know if there is some test that I would adopt.

**Checklist**

- [ ] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [x] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by damianpumar** [comment]
Hello @paulbauriegel 👋
Thanks for this contribution. 

I'll take a look!

**Comment by damianpumar** [comment]
Hello again @paulbauriegel
I tested your changes and it works! But we have some UI issues because some words are a bit long. 
Here I created a PR to switch language based on the browser language. https://github.com/argilla-io/argilla/pull/4690

Tomorrow we'll improve some UI bugs and we'll merge it.

Many thanks for this amazing contribution and keep improving Argilla together!!

**Comment by damianpumar** [comment]
Hello @paulbauriegel this morning we pushed one change into develop, now you can try your translation.
Before approve your PR could you please update the CHANGELOG.md

Thanks!

**Comment by paulbauriegel** [comment]
@damianpumar If you talk about #4690 it actually worked before too🤔. I think `detectBrowserLanguage` actually defaults to `useCookie: true` and that's why it might have worked in the browser. 
Anyway I can test it again & update the CHANGELOG.md

**Comment by paulbauriegel** [comment]
I tested it again, but I think it might make sense to add a couple more values to the translation js files
image

**Comment by paulbauriegel** [comment]
@damianpumar I added most of the changes that are relevant to have the feedback task and major UI elements multi-lingual. I would add the changes for other tasks like Text2Text etc in a second MR to make this one not too big. Changelog is updated if there is anything else Todo let me know.

**Comment by damianpumar** [comment]
Hi @paulbauriegel you can merge it when you want! 

Many thanks for your amazing work!

**Comment by paulbauriegel** [comment]
@damianpumar I don't have the rights to merge it myself, but please go ahead and merge it :-)

**Pull request merged**
