### PR TITLE
Docs/argilla trainer setfit tutorial

### LINKED ISSUE #3559: [DOCS] create tutorial on `ArgillaTrainer` with `setfit` and `FeedbackDataset`
## Which page or section is this issue related to?
N.A.

### PR DESCRIPTION
**Pull request by plaguss**
# Description

Adds a new tutorial on how to use the new `ArgillaTrainer` with `SetFit` to fine-tune a `FeedbackDataset` for `Label/MultiLabel` questions.

Closes #3559

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [x] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by plaguss** [comment]
Two local changes were needed for the `ArgillaTrainer` to work. 

1. This one is already waiting for a [PR](https://github.com/argilla-io/argilla/pull/3467) to be approved:

```diff
- df = df.explode(list(explode_columns))
+ if explode_columns:
+    df = df.explode(list(explode_columns))
```

2. Another error appears when training a model for `MultiLabelQuestion/MultiLabelStrategy`:

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/ipykernel_149926/2812279415.py:1 in <module>                                                │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_149926/2812279415.py'                       │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/argilla/client/feedback/tr │
│ aining/base.py:78 in __init__                                                                    │
│                                                                                                  │
│    75 │   │   self._seed = seed  # split is used for train-test-split and should therefore be    │
│    76 │   │   self._model = model                                                                │
│    77 │   │                                                                                      │
│ ❱  78 │   │   self._prepared_data = self._dataset.prepare_for_training(                          │
│    79 │   │   │   framework=framework,                                                           │
│    80 │   │   │   task_mapping=task_mapping,                                                     │
│    81 │   │   │   fetch_records=fetch_records,                                                   │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/argilla/client/feedback/da │
│ taset/base.py:357 in prepare_for_training                                                        │
│                                                                                                  │
│   354 │   │   else:                                                                              │
│   355 │   │   │   raise ValueError(f"Training data {type(task_mapping)} is not supported yet")   │
│   356 │   │                                                                                      │
│ ❱ 357 │   │   data = task_mapping._format_data([record for record in self.records])              │
│   358 │   │   if framework in [                                                                  │
│   359 │   │   │   Framework.TRANSFORMERS,                                                        │
│   360 │   │   │   Framework.SETFIT,                                                              │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/argilla/client/feedback/tr │
│ aining/schemas.py:69 in _format_data                                                             │
│                                                                                                  │
│ ❱  69 │   │   df = df.drop_duplicates()                                                          │
│    70 │   │   df = df.dropna(how="any")                                                          │
│    71 │   │   return df.to_dict(orient="records")                                                │
│    72                                                                                            │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py │
│ :331 in wrapper                                                                                  │
│                                                                                                  │
│   328 │   │   │   │   │   FutureWarning,                                                         │
│   329 │   │   │   │   │   stacklevel=find_stack_level(),                                         │
│   330 │   │   │   │   )                                                                          │
│ ❱ 331 │   │   │   return func(*args, **kwargs)                                                   │
│   332 │   │                                                                                      │
│   333 │   │   # error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no                         │
│   334 │   │   # attribute "__signature__"                                                        │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/core/frame.py:6672  │
│ in drop_duplicates                                                                               │
│                                                                                                  │
│    6669 │   │                                                                                    │
│    6670 │   │   inplace = validate_bool_kwarg(inplace, "inplace")                                │
│    6671 │   │   ignore_index = validate_bool_kwarg(ignore_index, "ignore_index")                 │
│ ❱  6672 │   │   duplicated = self.duplicated(subset, keep=keep)                                  │
│    6673 │   │                                                                                    │
│    6674 │   │   result = self[-duplicated]                                                       │
│    6675 │   │   if ignore_index:                                                                 │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/core/frame.py:6814  │
│ in duplicated                                                                                    │
│                                                                                                  │
│    6811 │   │   │   result.name = None                                                           │
│    6812 │   │   else:                                                                            │
│    6813 │   │   │   vals = (col.values for name, col in self.items() if name in subset)          │
│ ❱  6814 │   │   │   labels, shape = map(list, zip(*map(f, vals)))                                │
│    6815 │   │   │                                                                                │
│    6816 │   │   │   ids = get_group_index(                                                       │
│    6817 │   │   │   │   labels,                                                                  │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/core/frame.py:6782  │
│ in f                                                                                             │
│                                                                                                  │
│    6779 │   │   │   return self._constructor_sliced(dtype=bool)                                  │
│    6780 │   │                                                                                    │
│    6781 │   │   def f(vals) -> tuple[np.ndarray, int]:                                           │
│ ❱  6782 │   │   │   labels, shape = algorithms.factorize(vals, size_hint=len(self))              │
│    6783 │   │   │   return labels.astype("i8", copy=False), len(shape)                           │
│    6784 │   │                                                                                    │
│    6785 │   │   if subset is None:                                                               │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/core/algorithms.py: │
│ 822 in factorize                                                                                 │
│                                                                                                  │
│    819 │   │   │   │   # Don't modify (potentially user-provided) array                          │
│    820 │   │   │   │   values = np.where(null_mask, na_value, values)                            │
│    821 │   │                                                                                     │
│ ❱  822 │   │   codes, uniques = factorize_array(                                                 │
│    823 │   │   │   values,                                                                       │
│    824 │   │   │   na_sentinel=na_sentinel_arg,                                                  │
│    825 │   │   │   size_hint=size_hint,                                                          │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/.venv/lib/python3.10/site-packages/pandas/core/algorithms.py: │
│ 578 in factorize_array                                                                           │
│                                                                                                  │
│    575 │   hash_klass, values = _get_hashtable_algo(values)                                      │
│    576 │                                                                                         │
│    577 │   table = hash_klass(size_hint or len(values))                                          │
│ ❱  578 │   uniques, codes = table.factorize(                                                     │
│    579 │   │   values,                                                                           │
│    580 │   │   na_sentinel=na_sentinel,                                                          │
│    581 │   │   na_value=na_value,                                                                │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/docs/_source/guides/llms/examples/pandas/_libs/hashtable_clas │
│ s_helper.pxi:5943 in pandas._libs.hashtable.PyObjectHashTable.factorize                          │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/home/agustin/github_repos/argilla/docs/_source/guides/llms/examples/pandas/_libs/hashtable_cla │
│ ss_helper.pxi'                                                                                   │
│                                                                                                  │
│ /home/agustin/github_repos/argilla/docs/_source/guides/llms/examples/pandas/_libs/hashtable_clas │
│ s_helper.pxi:5857 in pandas._libs.hashtable.PyObjectHashTable._unique                            │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/home/agustin/github_repos/argilla/docs/_source/guides/llms/examples/pandas/_libs/hashtable_cla │
│ ss_helper.pxi'                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unhashable type: 'list'
```

It happens when dealing with a `pd.DataFrame` containing a column with lists, like the dataset used in the tutorial when training for the *topics*:

```bash
                                                text           label
0                           How do I locate my card?  [card_arrival]
1  I still have not received my new card, I order...  [card_arrival]
2  I ordered a card but it has not arrived. Help ...  [card_arrival]
3   Is there a way to know when my card will arrive?  [card_arrival]
4                       My card has not arrived yet.  [card_arrival]
5                           When will I get my card?  [card_arrival]
6  Do you know if there is a tracking number for ...  [card_arrival]
7                        i have not received my card  [card_arrival]
```

I don't know if something was wrong by my side, but for the moment, the following change does the trick:

```diff
- df = df.drop_duplicates()
+ if not df.applymap(lambda x: isinstance(x, list)).all().any():
+     df = df.drop_duplicates()
```

It checks the columns that contain lists (happens with `MultiLabel` datasets in the *label* column), and for those datasets we don't drop the possible duplicates. The tests for the trainer are all passing after this change, but maybe the change is quite naive. If this is a bug and not my error please let me know and I can open and issue and solve it properly (or maybe add it with the changes in [this PR](https://github.com/argilla-io/argilla/pull/3467)).

**Comment by davidberenstein1957** [comment]
HI @plaguss, opening an issue and corresponding PR would be best 💪🏽

**Comment by davidberenstein1957** [comment]
@plaguss The PR looks great already! However, maybe it is better to use a pre-trained transformer model or zero-shot model to infer initial predictions and emphasize that this can be used to provide initial predictions in other real-world use cases too.

**Comment by plaguss** [comment]
> HI @plaguss, opening an issue and corresponding PR would be best 💪🏽

for sure!

**Comment by plaguss** [comment]
> @plaguss The PR looks great already! However, maybe it is better to use a pre-trained transformer model or zero-shot model to infer initial predictions and emphasize that this can be used to provide initial predictions in other real-world use cases too.

Perfect! I will update that :ok_hand:

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
