### PR TITLE
docs: improve annotate records section in web app reference

### PR DESCRIPTION
**Pull request by dcfidalgo**
See the changes here: https://rubrix.readthedocs.io/en/feat-improve_webapp_ref/reference/webapp/annotate_records.html

### CODE REVIEW

**Comment by leireropl** [comment]
Images added, let me know if they are okay!

**Comment by dcfidalgo** [comment]
Great, thanks a lot! 2 small comments:
- `create_newlabel`: Could you make this a bit smaller, just cropping the lower part, similar to the `bulk_annotate.png`
- `text2text_annotation`: The same screenshot, but with the progress metrics closed

**Comment by leireropl** [comment]
> Great, thanks a lot! 2 small comments:
> 
> * `create_newlabel`: Could you make this a bit smaller, just cropping the lower part, similar to the `bulk_annotate.png`
> * `text2text_annotation`: The same screenshot, but with the progress metrics closed

Done! Hope these ones work :)

**Comment by dcfidalgo** [comment]
:100: Thanks a lot! Merging this one

**Pull request merged**
