### PR TITLE
Add explanation on which columns are used/ignore

### LINKED ISSUE #2696: [Docs] See which columns are read in `rg.read_datasets`
**Is your feature request related to a problem? Please describe.**
When using [`rg.read_datasets`](https://docs.argilla.io/en/latest/reference/python/python_client.html?highlight=loading%20datasets#argilla.client.datasets.read_datasets), I want to know which columns will be read. For example, when reading a Dataset with a `ner_tags` column for Token Classification, that column will unexpectedly be ignored.

**Describe the solution you'd like**
I want to be able to read which columns get read in the documentation or docstring of `rg.read_datasets`.

**Describe alternatives you've considered**
Stick with the current situation of requiring users to pay close attention to the logged warnings, which show e.g.
```
WARNING:argilla.client.datasets:Following columns are not supported by the TokenClassificationRecord model and are ignored: ['ner_tags', 'fine_ner_tags']
```

**Additional context**
https://docs.argilla.io/en/latest/reference/python/python_client.html?highlight=loading%20datasets#argilla.client.datasets.read_datasets

### PR DESCRIPTION
**Pull request by tomaarsen**
# Description

Closes #2696
The intention is to link to https://docs.argilla.io/en/latest/reference/python/python_client.html#module-argilla.client.models using Sphinx.

**Type of change**

- [x] Documentation update

**How Has This Been Tested**
N\A

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] I added relevant documentation
- [x] follows the style guidelines of this project
- N/A I did a self-review of my code
- [x] I made corresponding changes to the documentation
- N/A My changes generate no new warnings
- N/A I have added tests that prove my fix is effective or that my feature works
- N/A I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by tomaarsen** [comment]
This is on pause due to issues with building the [docs](https://readthedocs.org/projects/argilla-docs/builds/20114235/)

**Comment by tomaarsen** [comment]
The docs have been built, see [here](https://docs.argilla.io/en/docs-read_datasets/reference/python/python_client.html#argilla.client.datasets.read_datasets). This is ready for review now :)

**Comment by davidberenstein1957** [comment]
Hi @tomaarsen, could you also add a warning about the columns that have been dropped?

**Comment by tomaarsen** [comment]
I'll tackle it today 💪

**Comment by tomaarsen** [comment]
Apologies, haven't gotten around to it yet. 
Although I vaguely remember that there's already a warning. I'll see if that's the case or not.

**Comment by tomaarsen** [comment]
There's indeed already a warning, I forgot about it, but I already described the warning in #2696, e.g.:
```
WARNING:argilla.client.datasets:Following columns are not supported by the TokenClassificationRecord model and are ignored: ['ner_tags', 'fine_ner_tags']
```

This should be ready for review. @davidberenstein1957

**Review by davidberenstein1957 — APPROVED** [review]

**Comment by davidberenstein1957** [comment]
@tomaarsen up yo merge:)

**Pull request merged**
