### PR TITLE
feat: 1914 Allow to launch the argilla server in a different base_url

### LINKED ISSUE #1914: Allow to launch the argilla server in a  different `base_url`
**Is your feature request related to a problem? Please describe.**
Some server integrations are using proxies to forward the argilla server UI under a subpath, but for those cases, the integration is not working. (See #1899)

**Describe the solution you'd like**
We need to improve the way the application UI is served in addition to allowing the setting of the FastAPI base URL parameter.

**Describe alternatives you've considered**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by keithCuniah**
# Description

This PR allows specifying a different base URL for the argilla server execution. This can be helpful when the argilla server is running behind a proxy.

Launch argilla as follows:
```bash
ARGILLA_BASE_URL=/this-is-argilla python -m argilla
```
to launch the argilla server in `http://localhost:6900/this-is-argilla`

Closes #1914 

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] I added comments to my code
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by frascuchon** [comment]
When I was working on that, I saw some places using directly `nuxt start` command

Take a look into this issue for more details:
https://github.com/nuxt/nuxt.js/issues/1947

**Comment by frascuchon** [comment]
The several options used do not fit the expected solution. So we will tackle it in a custom way. 

1. [FrontEnd]: Allow to set up the `router.base` value (the `BASE_URL` env var is used for that in the nuxt.config.js file)
2. [Python server]: Allow to define a base URL where launch the server (`ARGILLA_BASE_URL`) 
3. [Build & start]: When statics are built, the `BASE_URL` variable used to generate will by `@@baseUr@@`.  On server startup, this value will be replaced by he provided in `settings.base_url` (`ARGILLA_BASE_URL` env)

@rhoitjadhav can you take a look at the final solution? Is there another way to do this properly?

**Comment by rhoitjadhav** [comment]
Looks fine to me.

**Review by rhoitjadhav — APPROVED** [review]

**Comment by rhoitjadhav** [comment]
Just out of curiosity, if argilla-server is running behind the proxy then its the proxy server's responsibility to configure the application url. I saw this on FASTApi [docu](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#about-proxies-with-a-stripped-path-prefix). Please correct me if any.

**Comment by frascuchon** [comment]
> Just out of curiosity, if argilla-server is running behind the proxy then its the proxy server's responsibility to configure the application url. I saw this on FASTApi [docu](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#about-proxies-with-a-stripped-path-prefix). Please correct me if any.

Yes, that's correct for those cases where FastAPI is serving only the API endpoints, no web app resources. 

In our case, we're serving also statics files that contain references to other files in the statics folder (for example an HTML page referring to a minified js file). For those cases, we need to align the proxy prefix with the base path URL for the argilla server. Otherwise, we can have problems like those found in #1899

**Review by davidberenstein1957 — APPROVED** [review]
looks fine to me too

**Pull request merged**
