### PR TITLE
Changing video format to webm

### LINKED ISSUE #153: Change documentation video format to .webm
At the moment Safari does not support webm format

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #153 

PR on hold, webm is not supported by Safari.

### CODE REVIEW

**Comment by frascuchon** [comment]
Any advances here? Could we use another video format ?

**Comment by frascuchon** [comment]
https://discussions.apple.com/thread/252503189

**Comment by ignacioct** [comment]
> https://discussions.apple.com/thread/252503189

It seems that now, on Big Sur 11.3, it is supported on Safari. I could try it (I'm not on 11.3 but I could move to), but probably most of the users will not be on that same version. What do you guys think?

**Comment by frascuchon** [comment]
> > https://discussions.apple.com/thread/252503189
> 
> It seems that now, on Big Sur 11.3, it is supported on Safari. I could try it (I'm not on 11.3 but I could move to), but probably most of the users will not be on that same version. What do you guys think?

Any other video format supporting apple's lovers?

**Comment by dvsrepo** [comment]
@ignacioct let's use this gif with an `img` tag (full-width): https://github.com/dvsrepo/imgs/blob/main/0shot_explore.gif

**Comment by ignacioct** [comment]
It's done @dvsrepo. Looking good to me on Safari and Chrome now. I'll go ahead and merge.

**Pull request merged**
