### PR TITLE
fix(quickstart): change default api key for the argilla quickstart image

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

Updating the default API-key for `argilla` user in the quickstart docker image.

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I added comments to my code
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tomaarsen** [comment]
👍 
I have to set my `ARGILLA_API_KEY` env variable to `rubrix.apikey` locally because the Docker containers (`argilla` and `quickstart`) still only responded to that, while the codebase had already started using `argilla.apikey`. This PR seems like it would fix that.

**Comment by frascuchon** [comment]
Thanks @tomaarsen 

Did you find this behavior also for the official `argilla-server` image?  The default `argilla.apikey` should work for that image

**Comment by tomaarsen** [comment]
Yes. These are my Argilla-related containers:
image

I tend only to use the ones that are active in that screenshot. I can only connect with the top container using `ARGILLA_API_KEY` as `rubrix.apikey`. If I remove that environment variable and run some code that interacts with `rg`, then I get the following traceback:

<details><summary>Click to see Traceback</summary>

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\code\argilla\.\issue_2353.py:3 in <module>                                                    │
│                                                                                                  │
│    1 import argilla as rg                                                                        │
│    2                                                                                             │
│ ❱  3 rg.delete("issue_2353_emoji")                                                               │
│    4                                                                                             │
│    5 tokens = ["💚", "a", "b", "c", "d", "💚", "e", "f", "g", "j", "k", "l"]                     │
│    6 text = "💚abcd💚efgjkl"                                                                     │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\api.py:294 in delete                                          │
│                                                                                                  │
│   291 │   │   >>> import argilla as rg                                                           │
│   292 │   │   >>> rg.delete(name="example-dataset")                                              │
│   293 │   """                                                                                    │
│ ❱ 294 │   ArgillaSingleton.get().delete(name)                                                    │
│   295                                                                                            │
│   296                                                                                            │
│   297 def delete_records(                                                                        │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\api.py:39 in get                                              │
│                                                                                                  │
│    36 │   @classmethod                                                                           │
│    37 │   def get(cls) -> Argilla:                                                               │
│    38 │   │   if cls._INSTANCE is None:                                                          │
│ ❱  39 │   │   │   return cls.init()                                                              │
│    40 │   │   return cls._INSTANCE                                                               │
│    41 │                                                                                          │
│    42 │   @classmethod                                                                           │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\api.py:62 in init                                             │
│                                                                                                  │
│    59 │   │   │   api_key=api_key,                                                               │
│    60 │   │   │   timeout=timeout,                                                               │
│    61 │   │   │   workspace=workspace,                                                           │
│ ❱  62 │   │   │   extra_headers=extra_headers,                                                   │
│    63 │   │   )                                                                                  │
│    64 │   │                                                                                      │
│    65 │   │   return cls._INSTANCE                                                               │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\client.py:156 in __init__                                     │
│                                                                                                  │
│   153 │   │   │   headers=headers.copy(),                                                        │
│   154 │   │   )                                                                                  │
│   155 │   │                                                                                      │
│ ❱ 156 │   │   self._user: User = users_api.whoami(client=self._client)                           │
│   157 │   │   if workspace is not None:                                                          │
│   158 │   │   │   self.set_workspace(workspace)                                                  │
│   159                                                                                            │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\users\api.py:20 in whoami                                 │
│                                                                                                  │
│   17                                                                                             │
│   18                                                                                             │
│   19 def whoami(client: AuthenticatedClient) -> User:                                            │
│ ❱ 20 │   response = client.get("/api/me")                                                        │
│   21 │   return User(**response)                                                                 │
│   22                                                                                             │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\client.py:125 in inner                                    │
│                                                                                                  │
│   122 │   │   @functools.wraps(func)                                                             │
│   123 │   │   def inner(self, *args, **kwargs):                                                  │
│   124 │   │   │   try:                                                                           │
│ ❱ 125 │   │   │   │   result = func(self, *args, **kwargs)                                       │
│   126 │   │   │   │   return result                                                              │
│   127 │   │   │   except httpx.ConnectError as err:  # noqa: F841                                │
│   128 │   │   │   │   return wrap_error(self.base_url)                                           │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\client.py:142 in get                                      │
│                                                                                                  │
│   139 │   │   │   *args,                                                                         │
│   140 │   │   │   **kwargs,                                                                      │
│   141 │   │   )                                                                                  │
│ ❱ 142 │   │   return build_raw_response(response).parsed                                         │
│   143 │                                                                                          │
│   144 │   @with_httpx_error_handler                                                              │
│   145 │   def patch(self, path: str, *args, **kwargs):                                           │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\_helpers.py:31 in build_raw_response                      │
│                                                                                                  │
│   28 def build_raw_response(                                                                     │
│   29 │   response: httpx.Response,                                                               │
│   30 ) -> Response[Union[Dict[str, Any], ErrorMessage, HTTPValidationError]]:                    │
│ ❱ 31 │   return build_typed_response(response)                                                   │
│   32                                                                                             │
│   33                                                                                             │
│   34 ResponseType = TypeVar("ResponseType")                                                      │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\_helpers.py:41 in build_typed_response                    │
│                                                                                                  │
│   38 │   response: httpx.Response,                                                               │
│   39 │   response_type_class: Optional[Type[ResponseType]] = None,                               │
│   40 ) -> Response[Union[ResponseType, ErrorMessage, HTTPValidationError]]:                      │
│ ❱ 41 │   parsed_response = check_response(response, expected_response=response_type_class)       │
│   42 │   if response_type_class:                                                                 │
│   43 │   │   parsed_response = response_type_class(**parsed_response)                            │
│   44 │   return Response(                                                                        │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\_helpers.py:70 in check_response                          │
│                                                                                                  │
│   67 │   │   │   message=message,                                                                │
│   68 │   │   │   response=response.content,                                                      │
│   69 │   │   )                                                                                   │
│ ❱ 70 │   handle_response_error(response, **kwargs)                                               │
│   71                                                                                             │
│                                                                                                  │
│ C:\code\argilla\src\argilla\client\sdk\commons\errors_handler.py:63 in handle_response_error     │
│                                                                                                  │
│   60 │   │   error_type = GenericApiError                                                        │
│   61 │   else:                                                                                   │
│   62 │   │   raise HttpResponseError(response=response)                                          │
│ ❱ 63 │   raise error_type(**error_args)                                                          │
│   64                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnauthorizedApiError: Argilla server returned an error with http status: 401
Error details: [{'code': 'argilla.api.errors::UnauthorizedError', 'params': {'detail': 'Could not validate
credentials'}}]
```
</details>

However, it must be stated that I created this container at 2023-02-09T11:54:17, which may be before the argilla-server image got updated?

**Comment by frascuchon** [comment]
Yes. The way to test with the latest version is by pulling the latest image and then, relaunching the container:

```bash
docker pull argilla-io/argilla-server:latest && docker compose up -d argilla 
```

**Pull request merged**
