### PR TITLE
SetFit dependency >= 1.0.0

### LINKED ISSUE #4435: [FEATURE] Update `ArgillaSetFitTrainer` to work with `setfit>=1.0.0`
**Is your feature request related to a problem? Please describe.**
Update the `ArgillaSetFitTrainer` so it works with `setfit>=1.0.0`

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #4435.

Updating SetFit to bump the version >= 1.0.0

**Type of change**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [X] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [x] Running the SetFit tutorial
- [x] Running SetFit tests on the suite

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@ignacioct looking good.

I believe during the evaluation step, we also have to explicitly define `metric_kwargs={"average": "micro|macro|weighted"}` for metrics like f1. Could you check to see how this works?

Also, could you configure the compatibility in such a way that is checks the version and keeps the old behavior for setfti < 1.0?

**Comment by ignacioct** [comment]
> `metric_kwargs={"average": "micro|macro|weighted"}` for metric
Screenshot 2024-01-26 at 12 21 46
@davidberenstein1957 I haven't found reference to these metric_kwargs, in setfit docs they just accept as parameter the testing dataset. Do you know where to find it?

**Comment by ignacioct** [comment]
> Also, could you configure the compatibility in such a way that is checks the version and keeps the old behavior for setfti < 1.0?

@davidberenstein1957 On my side, I think we should focus on the 1.0.0 functionality, as it's the first bigger release and it's the standard now if you do pip install. Everything else is working fine on my side :)

**Comment by ignacioct** [comment]
Getting some test errors, with a very similar trace

`FAILED tests/unit/client/feedback/schemas/test_records.py::test_feedback_record_update[schema_kwargs0-suggestions0-None-None] - pytest.PytestRemovedIn8Warning: Passing None has been deprecated.`

**Pull request merged**
