### PR TITLE
docs: spacy `DocBin` cookbook

### LINKED ISSUE #420: Add example to Cookbook to export training data for spaCy v3
Similar to the following example:

https://rubrix.readthedocs.io/en/stable/guides/cookbook.html#Training

Add example to transform a Rubrix dataset into a spaCy Docbin format and save it to disk (usable with the train spacy command for training)

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #420 

Following our work in #420 and #1635, I'm creating a small example into the Cookbook. Is this enough, or do we need something closer to an actual phrase or dataset?

### CODE REVIEW

**Comment by frascuchon** [comment]
Hi, @ignacioct, and thanks for your work!!

Maybe it could be nice to use a dataset and show a "real" workflow. The [`conll2003`](https://huggingface.co/datasets/conll2003) dataset could a candidate. You could do something like this:

```python
import spacy
import rubrix as rb

from datasets import load_dataset

ds = load_dataset("conll2003", split="train")
rds = rb.DatasetForTokenClassification.from_datasets(ds, tags="ner_tags")
nlp = spacy.blank("en")  # A blank nlp pipeline works faster

db = rds.prepare_for_training(framework="spacy", lang=nlp)
```

**Comment by ignacioct** [comment]
> ```python
> import spacy
> import rubrix as rb
> 
> from datasets import load_dataset
> 
> ds = load_dataset("conll2003", split="train")
> rds = rb.DatasetForTokenClassification.from_datasets(ds, tags="ner_tags")
> nlp = spacy.blank("en")  # A blank nlp pipeline works faster
> 
> db = rds.prepare_for_training(framework="spacy", lang=nlp)
> ```
Okay, using that dataset I believe there's one row unsupported, is this a problem for the example or we can go through?

```
2022-07-28 13:25:14.367 | WARNING  | datasets.builder:download_and_prepare:577 - Reusing dataset conll2003 (/Users/ignacio/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/63f4ebd1bcb7148b1644497336fd74643d4ce70123334431a3c053b7ee4e96ee)
2022-07-28 13:25:14.372 | WARNING  | rubrix.client.datasets:_remove_unsupported_columns:252 - Following columns are not supported by the TokenClassificationRecord model and are ignored: ['pos_tags', 'chunk_tags']
2022-07-28 13:25:16.324 | WARNING  | rubrix.client.datasets:from_datasets:761 - Ignoring row with no tokens.
```

**Comment by frascuchon** [comment]
No, It's okay. It's just a warning. You can go ahead. Thanks

**Comment by ignacioct** [comment]
That is already implemented, so we can go forward and merge then :) @frascuchon

**Review by frascuchon — APPROVED** [review]
Great!

**Pull request merged**
