### PR TITLE
Resolve many typos, clean up via `pre-commit`

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull request overview
* Discover typos via [`codespell`](https://github.com/codespell-project/codespell) and fix them in comments, the README, documentation and tutorials. 
* Run `pre-commit run --all` to perform reformatting, EOF fixing, removing redundant whitespace, etc. 

## Note
Surprisingly, running `pre-commit` introduced many changes, causing this PR to be a bit cluttered. Because of this, I'd recommend reviewing the two commits separately.

- Tom Aarsen

### CODE REVIEW

**Comment by frascuchon** [comment]
Hi @tomaarsen and thanks so much for your work.

If you don't mind, I will create a separate PR including only fixes about the `pre-commit` changes (and include some CI checks to avoid them in the future). Once is done, you could just keep only typo fixes.

**Comment by tomaarsen** [comment]
Seems good!

If you ever run into issues with https://pre-commit.ci/, you can defer to their now-deprecated GitHub action, which can be used like so:
https://github.com/nltk/nltk/blob/2e9cf65072f8cecdc5f2beaa7a66ac8de8f5b31e/.github/workflows/ci.yaml#L20-L26

I did a tiny bit of testing with your approach from #1703, but had not gotten around to applying it fully. I'll be following this to see if it works well for Rubrix!

**Comment by frascuchon** [comment]
Thanks @tomaarsen 

Finally, I could configure properly the pre-commit checks so new changes in the repo will auto-fix by the pre-commit.ci module. Maybe you find some conflict error if you try to bring changes from the master master branch.

**Comment by tomaarsen** [comment]
Glad you got it working!

Do you need anything from me to get this PR ready for merging?

**Comment by frascuchon** [comment]
I don't think so. I will tell you if I need your help. Thanks!!

**Review by frascuchon — APPROVED** [review]

**Pull request merged**
