### PR TITLE
Enhancement: extend shortcuts to include alphabet for token classification

### PR DESCRIPTION
**Pull request by cceyda**
# Description

This is a stop-gap solution to issue https://github.com/argilla-io/argilla/issues/1852
A more sophisticated solution can be found but in the mean time this solves the inconvenience when there are tags more than 10. 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [ ] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I added comments to my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tomaarsen** [comment]
I understand that this is designed as a simple temporary solution, but I want to point out that this will only work for the "default" QWERTY keyboard layout. Users on QWERTZ, AZERTY or others would likely find this unintuitive.

**Comment by cceyda** [comment]
okay realized shortcuts are uppercased in [code](https://github.com/argilla-io/argilla/blob/91a77ad85244cd885fafd40c38251ecdf2e37147/frontend/components/token-classifier/results/EntitiesSelector.vue#L126) so changed that. 

Also if anyone is looking for a quick custom shortcutkeys fix:
(chrome) using developer tools search for "1234567890" in js files, there should be 2.
then override, reload should work!

**Comment by dvsrepo** [comment]
thanks so much @cceyda for the PR. I would vote to merge this and tackle the keyboard layout configuration mentioned by @tomaarsen as part of the new Dataset Setting feat #2003 (maybe not for the first version but for following releases, that would be configurable there). what do you think @leiyre @Amelie-V ?

Could you review this PR @leiyre ?

**Review by leiyre — APPROVED** [review]
👌

**Comment by dvsrepo** [comment]
@leiyre could this be merged already?

**Comment by keithCuniah** [comment]
Hello everyone.
Just for information, as mention by @dvsrepo, this correction has also impact in dataset settings feature. See #[2444](https://github.com/argilla-io/argilla/pull/2444). So I moved the solution to the the front ORM.

Second things, I was looking for a way to get the user keyboard layout dynamically (which could solve the problem pointed by @tomaarsen), and there is a keyboard API in javascript for that but it's experimental (see this [link](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard)).  
So when this API will be stable, it would be a nice solution to have dynamical shorcuts depending on the users keyboard.

**Pull request merged**
