### PR TITLE
feat: Add basic support to bool features

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

Also, relax type casting for metadata values, accepting Any.

**Type of change**

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (change restructuring the codebase without changing functionality)
- Improvement (change adding some improvement to an existing functionality)
- Documentation update

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- I followed the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by burtenshaw — APPROVED** [review]
From my understanding, this slackens metadata typing to `Any`. That makes sense for current changes to the direction. 

@frascuchon We probably now have a lot of redundant testing and docs?

**Comment by frascuchon** [comment]
> @frascuchon We probably now have a lot of redundant testing and docs?

This is an SDK change only. Not sure to understand your question completely

**Comment by burtenshaw** [comment]
@frascuchon should we include tests here: argilla/tests/unit/test_settings/test_metadata.py

**Comment by frascuchon** [comment]
> @frascuchon should we include tests here: argilla/tests/unit/test_settings/test_metadata.py

Not really, we are just changing the metadata content, not the settings definition. But it makes sense to change the settings to accept not only str values. I will create a separate PR adding the change on the server side.

**Pull request merged**
