### PR TITLE
new folder and images for spacy tutorial

### PR DESCRIPTION
**Pull request by leireropl**
Actions:

-A new folder for the tutorial has been added,
- Images/videos have been updated,
- Former pictures have been deleted.

### CODE REVIEW

**Review by dcfidalgo — COMMENTED** [review]
Thanks @leireropl ! The new gifs seem to have a much worse resolution compared to the old ones. Would it be possible to improve the resolution for the new ones?

**Comment by leireropl** [comment]
> Thanks @leireropl ! The new gifs seem to have a much worse resolution compared to the old ones. Would it be possible to improve the resolution for the new ones?

Done!

**Comment by dcfidalgo** [comment]
@leireropl Just a minor thing, could you remove the gifs/files we don't need anymore?

**Comment by frascuchon** [comment]
Yesterday I was trying the spacy tutorial and I remark that the executable shell imports rubrix 

Screenshot 2021-12-16 at 11 52 11

If we skip the cell execution (since we can have already installed deps or the notebook kernel is restarted), the record generation will fail (since rubrix was not imported)
Screenshot 2021-12-16 at 11 53 36

Should be better to import rubrix modeul the first time is used in the notebook ?

@dvsrepo @leireropl ??

**Comment by dcfidalgo** [comment]
Yes, definitely a bug, I will push some changes to this PR.

**Pull request merged**
