### PR TITLE
updated readme with `conda` install instruction

### LINKED ISSUE #781: Add conda installation option for rubrix
Add a `conda` installation option for `rubrix`. I have already stared working on this one. It has passed all the CI's and will soon be merged. Once the :bulb: [**PR**][#pr-conda-forge-rubrix] gets approved/merged, `rubrix` will be available on conda-forge as:

[#pr-conda-forge-rubrix]: https://github.com/conda-forge/staged-recipes/pull/17234

```sh
conda install -c conda-forge rubix
```

:zap: Once `rubrix` is available on `conda-forge`, I will push a PR to update the readme-installation section.

### PR DESCRIPTION
**Pull request by sugatoray**
This closes #781. 

- [x] added conda installation instruction (`rubrix` is available on `conda-forge` channel)
- [x] added badges: 
  - [x] conda-forge/rubrix (with version)
  - [x] conda-forge/rubrix (with platform specification): example -- "noarch"
  - [x] docs badge

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @dvsrepo

**Comment by dvsrepo** [comment]
🚀 Wow! Thanks so much @sugatoray . As a final touch, would you include the conda install section here?

https://github.com/recognai/rubrix/blob/master/docs/getting_started/setup%26installation.rst#1-install-the-rubrix-python-client

Basically the same as in the README.

Otherwise no worries the team can do it on a next PR.

Btw, are you on Twitter? We tried to thank all contributions, especially awesome ones as this one

**Comment by sugatoray** [comment]
Sure. Will do.

> **Done**

**Comment by sugatoray** [comment]
> Btw, are you on Twitter? We tried to thank all contributions, especially awesome ones as this one

Yes. My twitter handle is `@sugatoray`. 

Twitter Follow

**Review by dvsrepo — APPROVED** [review]
💯 👏

**Comment by sugatoray** [comment]
@dvsrepo Could you please designate someone from your team, who could be added as another maintainer of [`conda-forge/rubrix-feedstock`](https://github.com/conda-forge/rubrix-feedstock) (apart from myself)? I personally believe, it is best to have at least one maintainer for the conda-forge feedstock who is also actively involved with the library. This will help ensure timely updates of the conda-forge version, whenever you have a PyPI release.

If it's okay, I could add you there as well. No worries, I will help you out with what you need to do after each PyPI release. It's mostly pretty straight forward.

**Comment by dvsrepo** [comment]
Maybe @frascuchon or @dcfidalgo ?

**Comment by sugatoray** [comment]
@dvsrepo Are you on LinkedIn? I just shared a post there about Rubrix being available on conda-forge.

[LinkedIn Post on Rubrix](https://www.linkedin.com/posts/sugatoray_condaforge-conda-anaconda-activity-6875106844457668609-CAb1)

**Comment by sugatoray** [comment]
@dvsrepo Would it be possible for you to add me to the list of contributors?

**Comment by dvsrepo** [comment]
> @dvsrepo Would it be possible for you to add me to the list of contributors?

Done! I've added a new section to the README

**Comment by sugatoray** [comment]
> Maybe @frascuchon or @dcfidalgo ?

@dvsrepo Who to add to the conda-forge feedstock for `rubrix` as a maintainer (apart from me)?

**Comment by dcfidalgo** [comment]
@sugatoray Would it be possible to add both of us, that is @frascuchon and me?

**Comment by sugatoray** [comment]
@dcfidalgo Yes, that should not be a problem. But, let's first get you acquainted with the process. 

Please take a look at `recipe/meta.yaml` file in the repo: `conda-forge/rubrix-feedstock`.

After every PyPI release, you need to update this file with:

- version 
- sha256
- make updates to dependency specifications (the same as your `setup.py:install_requires`), if necessary under run-requirements. 

All three above must match that with your PyPI release.

Please feel free to ask me if you have any questions.

**Comment by dcfidalgo** [comment]
Thanks a lot for this brief summary @sugatoray. Maybe we will have a release this week, do you mind if I take care of the conda release, just to get some experience with it?

**Comment by sugatoray** [comment]
That sounds perfect! Yes, please submit a PR to do the conda-forge package update, once the PyPI release happens.

**Pull request merged**
