### PR TITLE
Docs/feedback setfit tutorial

### LINKED ISSUE #3528: [Docs] Setfit 🤝 Feedback tutorial

### PR DESCRIPTION
**Pull request by nataliaElv**
# Description

Adds a new tutorial on how to use SetFit to get zero-shot suggestions for `Label` and `MultiLabel` questions in Feedback datasets.

Closes #3528 

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [x] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [ ] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by tomaarsen — CHANGES_REQUESTED** [review]
At a glance, I have a bit of feedback regarding formatting:
```python
def get_predictions(texts, model, question_name):
    probas = model.predict_proba(texts, as_numpy=True)
    for pred in probas:
        yield [{"label": label, "score": score} for label, score in zip(dataset.question_by_name(question_name).labels, pred)]
```
can become:
```python
def get_predictions(texts, model, question_name):
    probas = model.predict_proba(texts, as_numpy=True)
    labels = dataset.question_by_name(question_name).labels
    for pred in probas:
        yield [{"label": label, "score": score} for label, score in zip(labels, pred)]
```
I'm not sure if `dataset.question_by_name(question_name).labels` is expensive or not, but regardless, this is a bit easier to read. 
Alternatively, you can also format it like this:
```python
def get_predictions(texts, model, question_name):
    probas = model.predict_proba(texts, as_numpy=True)
    labels = dataset.question_by_name(question_name).labels
    for pred in probas:
        yield [
            {"label": label, "score": score}
            for label, score in zip(labels, pred)
        ]
```

---

Secondarily, 
```python
data = data.map(lambda batch: {"topics": list(get_predictions(batch['text'], topic_model, "topics")),"sentiment": list(get_predictions(batch['text'], sentiment_model, "sentiment"))}, batched=True)
```
should really be formatted like:
```python
data = data.map(
    lambda batch: {
        "topics": list(get_predictions(batch["text"], topic_model, "topics")),
        "sentiment": list(get_predictions(batch["text"], sentiment_model, "sentiment")),
    },
    batched=True,
)
```
That's much easier to read I think.

---

```python
def add_suggestions(record):
    suggestions = []
    
    # get label with max score for sentiment question
    sentiment = max(record['sentiment'], key=lambda x: x['score'])['label']
    suggestions.append({"question_name": "sentiment", "value": sentiment})

    # get all labels above a threshold for topics questions
    topics = [label['label'] for label in record['topics'] if label['score'] >= 2/len(dataset.question_by_name("topics").labels)]
    # apply the suggestion only if at least one label was over the threshold
    if topics:
        suggestions.append({"question_name": "topics", "value": topics})
    return suggestions
```
We can probably turn the threshold into a variable for clarity:

```python
def add_suggestions(record):
    suggestions = []
    
    # get label with max score for sentiment question
    sentiment = max(record['sentiment'], key=lambda x: x['score'])['label']
    suggestions.append({"question_name": "sentiment", "value": sentiment})

    # get all labels above a threshold for topics questions
    threshold = 2 / len(dataset.question_by_name("topics").labels)
    topics = [label['label'] for label in record['topics'] if label['score'] >= threshold]
    # apply the suggestion only if at least one label was over the threshold
    if topics:
        suggestions.append({"question_name": "topics", "value": topics})
    return suggestions
```

---

```python
records = [rg.FeedbackRecord(fields={"text":record['text']}, suggestions=add_suggestions(record)) for record in data]
```
should either be
```python
records = [rg.FeedbackRecord(fields={"text": record['text']}, suggestions=add_suggestions(record)) for record in data]
```
(a new space)
or 
```python
records = [
    rg.FeedbackRecord(fields={"text": record['text']}, suggestions=add_suggestions(record))
    for record in data
]
```

---

Can we get a screenshot of an un-annotated record in Argilla with the suggestions applied or something? Then users can see what it does.

**Comment by nataliaElv** [comment]
> 
> Can we get a screenshot of an un-annotated record in Argilla with the suggestions applied or something? Then users can see what it does.

Thanks for the suggestions! I think they make the code much more readable, so I'll certainly apply them. 

About the screenshot that you mention. There is one at the start of the notebook, but I can move (or add) it down here if it makes more sense.

**Comment by tomaarsen** [comment]
Oh, oops. I forgot about it by the time I got to the bottom. 
I think it would be fine to have the screenshot in two places, or maybe use a slightly different sample for the 2nd screenshot or something.

**Comment by tomaarsen** [comment]
Looks great! Perhaps a link to other SetFit tutorials at the end? And/or to SetFit itself?
Something like [here](https://docs.argilla.io/en/latest/tutorials/notebooks/training-textclassification-setfit-fewshot.html#Conclusion)

We don't have to have this though, as these other tutorials dont use the Feedback Dataset

**Comment by tomaarsen** [comment]
I don't see the tutorial here: https://docs.argilla.io/en/docs-feedback-setfit-tutorial/tutorials/libraries/setfit.html
Maybe we can add a link there? 

Other than that, it looks good.

**Pull request merged**
