### PR TITLE
Updating videos for NER-related tutorials

### LINKED ISSUE #1182: [Tutorials] Update videos and screenshots for Token classification
All tutorials and guides showing token classification task UI, should be updated with new UI

### PR DESCRIPTION
**Pull request by leireropl**
Several videos (and images) are pending for several tutorials. 

I uploaded the one for spaCy. I will update pictures in a different commit.

Close #1182

### CODE REVIEW

**Comment by dcfidalgo** [comment]
@Amelie-V Could you have a look? https://raw.githubusercontent.com/recognai/rubrix/bba690946745772bff975a2eac7bf77a5b38b530/docs/_static/tutorials/02-spacy/spacy.mp4

**Comment by leireropl** [comment]
I think this is it. Let me know if I am missing anything or give me feedback.

**Comment by Amelie-V** [comment]
Soory I just read that....now 

I would recommend to have the new header implemented in that video, and also the fine tuning of NER integrated

**Comment by frascuchon** [comment]
Closing. See #1216

**Comment by frascuchon** [comment]
Closing. Resolved in #1216

**Pull request closed without merging**
