### PR TITLE
docs: Remove pre-training section & rename fine_tune docs

### PR DESCRIPTION
**Pull request by tomaarsen**
# Description

* Remove the `pre-training` section from the [docs](https://docs.argilla.io/en/develop/guides/llms/practical_guides/fine_tune.html#pre-training).
* Rename `Fine-tuning a Feedback Dataset` to `Fine-tuning language models with Feedback Datasets`

**Type of change**

- [x] Documentation update

**How Has This Been Tested**

It hasn't, I'll check the auto build for this PR

**Checklist**

- [x] I added relevant documentation
- [x] I followed the style guidelines of this project
- [x] I did a self-review of my code
- [x] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

---

- Tom Aarsen

### CODE REVIEW

**Review by davidberenstein1957 — APPROVED** [review]

**Comment by tomaarsen** [comment]
I found some refs to the removed section, updating now

**Comment by davidberenstein1957** [comment]
shoot @tomaarsen, I think we also want to change this in the release branch. Can you cherry-pick the commits and create another PR for the release too?

**Comment by tomaarsen** [comment]
Makes total sense, will do

**Comment by tomaarsen** [comment]
Ah shit, I totally lost track of this. Should we merge this into dev and main now?

**Comment by dvsrepo** [comment]
> Ah shit, I totally lost track of this. Should we merge this into dev and main now?

Yes, not a big deal. We can move it to develop and most important is main

**Comment by tomaarsen** [comment]
Pointed this PR to main as that's most important and I can merge main into dev more easily than the other way around. Rebased to get rid of the `develop`-only commits.

**Comment by tomaarsen** [comment]
& cherry-picked the commit into develop

**Pull request merged**
