### PR TITLE
fix: `POST /api/v1/datasets` doesn't handle non-existing workspace ids

### LINKED ISSUE #2753: API v1 `create_dataset` endpoint doesn't handle non-existing workspaces
**Describe the bug**
When creating a new dataset using the new endpoint `POST /api/v1/datasets` introduced in #2628, if the provided value in the body for the field `workspace_id` is not associated with any workspace, the endpoint will try to create a new dataset in the database but a `sqlalchemy.exc.IntegrityError` exception will be raised because the `workspace_id` foreign key constraint won't be satisfied.

<details>
<summary>Long traceback</summary>

```
Traceback (most recent call last):
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 918, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call_
_
    await super().__call__(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __
call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/brotli_asgi/__init__.py", line 81, in __call__
    await responder(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/brotli_asgi/__init__.py", line 125, in __call__
    await self.app(scope, receive, self.send_with_brotli)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/src/argilla/server/apis/v1/handlers/datasets.py", line 141, in create_dataset
    return datasets.create_dataset(db, dataset_create)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/src/argilla/server/contexts/datasets.py", line 57, in create_dataset
    db.commit()
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1905, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1220, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1195, in _prepare_impl
    self.session.flush()
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4153, in flush
    self._flush(objects)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4289, in _flush
    with util.safe_reraise():
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4250, in _flush
    flush_context.execute()
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1208, in _emit_insert_statements
    result = connection.execute(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1841, in _execute_context
    return self._exec_single_context(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/gabriel.martin/src/gabrielmbmb/argilla/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 918, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO datasets (id, name, guidelines, status, workspace_id, inserted_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4341207194044757b81d942800e827b1', 'test_dataset', 'bla bla bla', 'draft', '3fa85f6457174562b3fc2c963f66afa6', '2023-04-22 17:59:34.331418', '2023-04-22 17:59:34.331418')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

</details>

**To Reproduce**
1. `git checkout feat/2615-instructions-task`
2. `python -m argilla`
3. Call `POST /api/v1/datasets` with a `workspace_id` not associated with any workspace in the DB

**Expected behavior**
If a `workspace_id` is not associated with any workspace in the DB, then the endpoint should return `404`

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac OS Ventura 13.2.1
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]: 1.7.0.dev0
 - ElasticSearch Version [e.g. 7.10.2]: 8.5.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

### PR DESCRIPTION
**Pull request by gabrielmbmb**
# Description

I've updated the `POST /api/v1/datasets` endpoint to check if the `workspace_id` provided in the `body` of the request exists. If there is no `workspace` object associated to the provided id, the endpoint will return `404 Not Found`. I've also added a new unit test to cover this case.

Closes #2753 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (change restructuring the codebase without changing functionality)
- [x] Improvement (change adding some improvement to an existing functionality)
- [ ] Documentation update

**How Has This Been Tested**

- Manually:
  - I tried to create a dataset using the `POST /api/v1/datasets` endpoint and providing a non-existing `workspace_id`. I got `404`. No new rows were added to the DB.
- Unit Test

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@gabrielmbmb can this already be reviewed?

**Comment by gabrielmbmb** [comment]
Hi @davidberenstein1957. Yes, it is ready.

**Review by jfcalvo — COMMENTED** [review]
I'm not really sure if returning a 404 status it's a good approach when the body has a unexpected/non-existent `workspace_id`.

Things that we can do:
* Return a 500 error. (I think it's what we already have).
* Return a 422 error with a proper message.

What's the motivation behind this PR? What are we trying to solve?

**Comment by gabrielmbmb** [comment]
I think that the standard is to use `404` if a resource is not found.

For me returning `500` is not a good option, because it reflects that something unexpected and not well handled happened on the service, and `422` I think you want to use it when the user has provided some JSON that doesn't pass the input validations.

The main motivation for this PR was to handle the unexpected error that was occurring when passing a workspace id that does not exist.

**Comment by jfcalvo** [comment]
> I think that the standard is to use `404` if a resource is not found.

Returning a `404` error for `/api/v1/datasets` endpoint is like saying "sorry I can't find the datasets resource". It's a little bit weird and It's something we are not doing it on the APIv1.
 
> For me returning `500` is not a good option, because it reflects that something unexpected and not well handled happened on the service, and `422` I think you want to use it when the user has provided some JSON that doesn't pass the input validations.

If we don't want to return a generic 500 error and want to be more specific about what it's happening then I think it's correct to return a `422` error with a message. In fact the body it's fine but semantically incorrect because the `workspace_id` doesn't exists, and that matches with what a 422 response should be.

By the way if we want to do this then we should do it for all the APIv1 creation endpoints and not only for the one to create datasets. Additionally I would investigate if we can do this adding a validation to the Pydantic model receiving the creation attributes, specifically `DatasetCreate`.

> The main motivation for this PR was to handle the unexpected error that was occurring when passing a workspace id that does not exist.

Ok.

**Comment by frascuchon** [comment]
Sorry, I forgot to comment on this PR. Thanks for the contribution @gabrielmbmb 

I agree with the 422 status code. Make sense to return a 422 instead of a 404 since we provide the workspace id as part of the request body. 

Regarding the rest of the entity creation endpoints, Yes, we should align other similar endpoints but we can proceed with this proposal and tackle them in a separate PR (at least the update response one).

Please, apply the changes to the status response if make sense to you @gabrielmbmb. Then, that would be fine for me.

**Comment by gabrielmbmb** [comment]
Changes applied. Thanks for the review @jfcalvo and @frascuchon.

**Review by frascuchon — APPROVED** [review]

**Pull request merged**
