### PR TITLE
feat: allow pass extra config to search backend client

### LINKED ISSUE #2394: Feature request: Support AWS OpenSearch serverless as backend
After a discussion with @frascuchon on Slack, I add my feature request here for better trackability:

AWS recently released a serverless option for their OpenSearch service (which I currently use for my Argilla server). Using the serverless option would be really great for us since it removes the overhead of taking care of a cluster for OpenSearch and you only pay what you use, it scales automatically in peak times etc.

From what I see [here](https://github.com/awsdocs/amazon-opensearch-service-developer-guide/blob/master/doc_source/serverless-sdk.md), you can just use `opensearch-py` for interacting with the serverless variant as you would with the server version (see `def indexData` at the end of the python example). As far as I know, this is how Argilla talks to OpenSearch at the moment anyway.

My only concern is authentication. As far as I know, Argilla only supports basic authentication right now (I had to disable any other access control to make it work with the server version of AWS OpenSearch). The linked example above uses `requests_aws4auth.AWS4Auth` to provide AWS credentials with the appropriate rights to access/modify the data.
Seeing that this seems to be the only piece that is missing and that it seems to be already well supported by the `opensearch-py` library, it would be great if this was supported by Argilla in the near future.

It looks like specifying AWS credentials in some environment variable for the server and passing that down to the `opensearch-py` library could already be enough but, of course, I don't know all the details behind the scenes. Thank you for looking into that!

### PR DESCRIPTION
**Pull request by frascuchon**
# Description

This PR provides a way to fine-tune elastic backend connections for specific or custom environments (OpenSearch serverless, customized security authentication, extended timeout settings,....) 

Two new environment variables have been provided to support this: `ARGILLA_ELASTICSEARCH_EXTRA_ARGS` and `ARGILLA_OPENSEARCH_EXTRA_ARGS`. You use one of them depending on your backend configuration*

_*Note: This won't work for new feedback task datasets, since the client used is an OpenSearch instance, which is fully compatible with most use cases._

## Basic extra arguments confguration
```bash
export ARGILLA_ELASTICSEARCH_EXTRA_ARGS='{ "extra": "argument" }'
python -m argilla server
```

## Extended extra arguments configuration (more complex than a JSON spec)

Some extra arguments are other than built-in types, and you probably need to create some object instances to pass as an argument. For those cases, you can change the argilla server settings programmatically:

```python
# custom_main.py

import boto3

from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth
from argilla.server import app
from argilla.server.settings import settings


host = '' # cluster endpoint, for example: my-test-domain.us-east-1.aoss.amazonaws.com
region = 'us-west-2'
service = 'aoss'
credentials = boto3.Session().get_credentials()
auth = AWSV4SignerAuth(credentials, region, service)

settings.opensearch_extra_args.update(dict(
    hosts = [{'host': host, 'port': 443}],
    http_auth = auth,
    use_ssl = True,
    verify_certs = True,
    connection_class = RequestsHttpConnection,
    pool_maxsize = 20
))

app = app
```
and then launch the Argilla server using the uvicorn CLI directive:

```bash
UVICORN_PORT=6900 uvicorn custom_main:app
```

## Customizing with docker-compose

You can apply this custom approach event in dockerized environment. Just mount your `custom_main.py` in the root folder:
```yaml
...
    volumes:
      - ${PWD}/custom_main.py:/container_main.py
```
and set the uvicorn app to use by setting the `UVICORN_APP` environment variable:
```yaml
    environment:
      ...
      UVICORN_APP: container_main:app
```

Closes #2394

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [X] Improvement (change adding some improvement to an existing functionality)

**How Has This Been Tested**

Some tests have been added. Also, some local tests using a dockerized environment have been validated successfully.

**Checklist**

- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by mnschmit** [comment]
After some testing, I found that there's a problem with [this line](https://github.com/argilla-io/argilla/blob/08913f26f438c7caabfe0c32705cc77cfdcc4bd7/src/argilla/server/daos/backend/client_adapters/factory.py#L88) when I use the serverless AWS OpenSearch service. It leads to a 404 error.

I suppose we need a way to tell argilla that it's opensearch. For the version I found this:
> Serverless collections currently run OpenSearch version 2.0.x. As new versions are released, OpenSearch Serverless will automatically upgrade your collections to consume new features, bug fixes, and performance improvements.

I am not sure how to handle this with respect to vector support.

**Comment by mnschmit** [comment]
@frascuchon @davidberenstein1957

What do you think if the error handling in [this line](https://github.com/argilla-io/argilla/blob/08913f26f438c7caabfe0c32705cc77cfdcc4bd7/src/argilla/server/daos/backend/client_adapters/factory.py#L95) checked some environment variables for the distribution and version and only throws the `GenericSearchError` if the env variables are not set?
That would solve this particular problem with AWS serverless. I could just manually set it to `OpenSearch` and `2.0`.

**Comment by frascuchon** [comment]
Hi @mnschmit, sorry for the late response. Yes, I think we should support a way to inform Argilla which backend and backend version will be used to set up properly the client.

I will try something today.

**Comment by mnschmit** [comment]
Great, thank you, @frascuchon !
I'll be happy to test it :)

**Comment by frascuchon** [comment]
Hi @mnschmit.

I've refactored a bit the factory client. Now, when errors different than a connection error are raised, a basic client configuration will be setup. Let me know if you can test it.

**Comment by mnschmit** [comment]
Hi @frascuchon !

It took me a bit to get the permissions right in AWS, but now API calls get through from Argilla server to OpenSearch serverless. I still have trouble with [this line](https://github.com/argilla-io/argilla/blob/136dbbd307ea60b2774ef9b945121eb8de66cb83/src/argilla/server/daos/backend/client_adapters/opensearch.py#L167) though. Apparently, `get_cluster_info` of the `OpenSearchClient` adapter class is called when I open up the server UI and also when I try to log records into a dataset. I couldn't easily see where that happens, but I get an error from this line when I try either of these things.
Since the call `self.__client__.info()` is problematic with serverless setups, probably the method itself should handle such a case and exit more gracefully and/or with a warning again.

I hope we're close to figuring it out :)

**Comment by mnschmit** [comment]
Hi @frascuchon ! Did you have time to think about a possible solution? Can I help?

**Comment by frascuchon** [comment]
Sorry for the late response @mnschmit I've been quite busy the last few days. Let me take a look today. These workflows that you mention shouldn't check the elastic/opensearch connectivity. 

Thanks for your time and all this feedback.

**Comment by mnschmit** [comment]
Hi @frascuchon ! Thanks for making room in your busy schedule for this. It would be really great if we could make a serverless argilla possible.

Your last commit seems to touch something related to elasticsearch. Is this naming more specific than it should, or does it really only concern elastic search and not opensearch? In any case, I still have the same problem as before your change.
Maybe I misdiagnosed something because I don't know the code base well enough. In case it helps, I'll give you some more information this time (I tried to manually anonymize all references to my actual opensearch endpoint). I hope we can figure it out together.

# When I log into the server UI

This works. The server does not crash but shows me the usual screen when there are not datasets. It invites me to upload a new dataset.

## Server logs
```
“GET /api/workspaces HTTP/1.1" 200 OK	
“GET /api/v1/me/datasets HTTP/1.1" 200 OK
"GET /api/datasets/ HTTP/1.1" 200 OK



[07/18/23 09:56:43] WARNING  WARNING:opensearch:GET                  base.py:259
                             https://skui4y38ry9wh78.fake-region/                                                                                                                                                                                                                                                                                                                                                                    .aoss.amazonaws.com:443/ar.datasets/_            
                             mapping [status:N/A request:0.002s]                
                             Traceback (most recent call last):                 
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 714,             
                             in urlopen                                         
                                 httplib_response =                             
                             self._make_request(                                
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 466,             
                             in _make_request                                   
                                 six.raise_from(e, None)                        
                               File "<string>", line 3, in                      
                             raise_from                                         
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 461,             
                             in _make_request                                   
                                 httplib_response =                             
                             conn.getresponse()                                 
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 1377, in getresponse                      
                                 response.begin()                               
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 320, in begin                             
                                 version, status, reason =                      
                             self._read_status()                                
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 281, in _read_status                      
                                 line =                                         
                             str(self.fp.readline(_MAXLINE + 1),                
                             "iso-8859-1")                                      
                               File                                             
                             "/usr/local/lib/python3.9/socket.py",              
                             line 704, in readinto                              
                                 return self._sock.recv_into(b)                 
                               File                                             
                             "/usr/local/lib/python3.9/ssl.py", line            
                             1242, in recv_into                                 
                                 return self.read(nbytes, buffer)               
                               File                                             
                             "/usr/local/lib/python3.9/ssl.py", line            
                             1100, in read                                      
                                 return self._sslobj.read(len,                  
                             buffer)                                            
                             ConnectionResetError: [Errno 104]                  
                             Connection reset by peer                           
                                                                                
                             During handling of the above exception,            
                             another exception occurred:                        
                                                                                
                             Traceback (most recent call last):                 
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /requests/adapters.py", line 486, in               
                             send                                               
                                 resp = conn.urlopen(                           
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 798,             
                             in urlopen                                         
                                 retries = retries.increment(                   
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/util/retry.py", line 550, in              
                             increment                                          
                                 raise six.reraise(type(error),                 
                             error, _stacktrace)                                
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/packages/six.py", line 769, in            
                             reraise                                            
                                 raise value.with_traceback(tb)                 
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 714,             
                             in urlopen                                         
                                 httplib_response =                             
                             self._make_request(                                
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 466,             
                             in _make_request                                   
                                 six.raise_from(e, None)                        
                               File "<string>", line 3, in                      
                             raise_from                                         
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /urllib3/connectionpool.py", line 461,             
                             in _make_request                                   
                                 httplib_response =                             
                             conn.getresponse()                                 
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 1377, in getresponse                      
                                 response.begin()                               
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 320, in begin                             
                                 version, status, reason =                      
                             self._read_status()                                
                               File                                             
                             "/usr/local/lib/python3.9/http/client.p            
                             y", line 281, in _read_status                      
                                 line =                                         
                             str(self.fp.readline(_MAXLINE + 1),                
                             "iso-8859-1")                                      
                               File                                             
                             "/usr/local/lib/python3.9/socket.py",              
                             line 704, in readinto                              
                                 return self._sock.recv_into(b)                 
                               File                                             
                             "/usr/local/lib/python3.9/ssl.py", line            
                             1242, in recv_into                                 
                                 return self.read(nbytes, buffer)               
                               File                                             
                             "/usr/local/lib/python3.9/ssl.py", line            
                             1100, in read                                      
                                 return self._sslobj.read(len,                  
                             buffer)                                            
                             urllib3.exceptions.ProtocolError:                  
                             ('Connection aborted.',                            
                             ConnectionResetError(104, 'Connection              
                             reset by peer'))                                   
                                                                                
                             During handling of the above exception,            
                             another exception occurred:                        
                                                                                
                             Traceback (most recent call last):                 
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /opensearchpy/connection/http_requests.            
                             py", line 179, in perform_request                  
                                 response =                                     
                             self.session.send(prepared_request,                
                             **send_kwargs)                                     
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /requests/sessions.py", line 703, in               
                             send                                               
                                 r = adapter.send(request, **kwargs)            
                               File                                             
                             "/usr/local/lib/python3.9/site-packages            
                             /requests/adapters.py", line 501, in               
                             send                                               
                                 raise ConnectionError(err,                     
                             request=request)                                   
                             requests.exceptions.ConnectionError:               
                             ('Connection aborted.',                            
                             ConnectionResetError(104, 'Connection              
                             reset by peer'))                                   
INFO:     10.0.102.245:34774 - "GET /api/datasets/ HTTP/1.1" 200 OK
INFO:     10.0.102.245:34774 - "GET /api/v1/me/datasets HTTP/1.1" 200 OK
INFO:     10.0.102.245:34774 - "GET /api/workspaces HTTP/1.1" 200 OK
[07/18/23 09:56:44] WARNING  WARNING:opensearch:GET                  base.py:259
                             https://ldfj4o8tesfnsoduh.fake-region            
                             -1.aoss.amazonaws.com:443/ [status:404             
                             request:0.005s]                                    
                    ERROR    ERROR:argilla:NotFoundError(404, '')  adapter.py:32
INFO:     10.0.102.245:34774 - "GET /api/_info HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/base.py", line 81, in __exit__
    raise exception_value from exception_value
  File "/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/client_adapters/opensearch.py", line 167, in get_cluster_info
    return self.__client__.info()
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/client/utils.py", line 178, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/client/__init__.py", line 251, in info
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py", line 409, in perform_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py", line 370, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/connection/http_requests.py", line 219, in perform_request
    self._raise_error(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/connection/base.py", line 301, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.NotFoundError: NotFoundError(404, '')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/brotli_asgi/__init__.py", line 81, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/brotli_asgi/__init__.py", line 125, in __call__
    await self.app(scope, receive, self.send_with_brotli)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.9/site-packages/argilla/server/apis/v0/handlers/info.py", line 36, in api_info
    return ApiInfo.parse_obj(service.api_status())
  File "/usr/local/lib/python3.9/site-packages/argilla/server/services/info.py", line 92, in api_status
    elasticsearch=self._elasticsearch_info(),
  File "/usr/local/lib/python3.9/site-packages/argilla/server/services/info.py", line 98, in _elasticsearch_info
    return self.__es__.client.get_cluster_info()
  File "/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/client_adapters/opensearch.py", line 167, in get_cluster_info
    return self.__client__.info()
  File "/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/base.py", line 103, in __exit__
    raise IndexNotFoundError(ex)
argilla.server.daos.backend.base.IndexNotFoundError: NotFoundError(404, '')
```

# When I try to do `rg.init` in a python script

So I try to connect to the argilla server within a python script and this throws an error.

## Error in python script
```
GenericApiError: Argilla server returned an error with http status: 500
Error details: [{'code': 'argilla.api.errors::GenericServerError', 'params': {'type': 
'argilla.server.daos.backend.base.IndexNotFoundError', 'message': "NotFoundError(404, '')"}}]
```

## Server logs
```
"INFO:     10.0.102.245:23062 - ""GET /api/me HTTP/1.1"" 200 OK"
"INFO:     10.0.102.245:23062 - ""GET /api/me HTTP/1.1"" 200 OK"
"INFO:     10.0.102.245:23062 - ""GET /api/workspaces HTTP/1.1"" 200 OK"
[07/18/23 10:12:44] WARNING  WARNING:opensearch:GET                  base.py:259
                             https://sdfnsldjndl8u89we.fake-region            
                             -1.aoss.amazonaws.com:443/ [status:404             
                             request:0.025s]                                    
"                    ERROR    ERROR:argilla:NotFoundError(404, '')  adapter.py:32"
"INFO:     10.0.102.245:23062 - ""GET /api/_info HTTP/1.1"" 500 Internal Server Error"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/base.py"", line 81, in __exit__"
    raise exception_value from exception_value
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/client_adapters/opensearch.py"", line 167, in get_cluster_info"
    return self.__client__.info()
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/client/utils.py"", line 178, in _wrapped"
"    return func(*args, params=params, headers=headers, **kwargs)"
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/client/__init__.py"", line 251, in info"
    return self.transport.perform_request(
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py"", line 409, in perform_request"
    raise e
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py"", line 370, in perform_request"
"    status, headers_response, data = connection.perform_request("
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/connection/http_requests.py"", line 219, in perform_request"
    self._raise_error(
"  File ""/usr/local/lib/python3.9/site-packages/opensearchpy/connection/base.py"", line 301, in _raise_error"
"    raise HTTP_EXCEPTIONS.get(status_code, TransportError)("
"opensearchpy.exceptions.NotFoundError: NotFoundError(404, '')"
"During handling of the above exception, another exception occurred:"
Traceback (most recent call last):
"  File ""/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py"", line 419, in run_asgi"
    result = await app(  # type: ignore[func-returns-value]
"  File ""/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py"", line 78, in __call__"
"    return await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/applications.py"", line 270, in __call__"
"    await super().__call__(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/applications.py"", line 124, in __call__"
"    await self.middleware_stack(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py"", line 184, in __call__"
    raise exc
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py"", line 162, in __call__"
"    await self.app(scope, receive, _send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py"", line 79, in __call__"
    raise exc
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py"", line 68, in __call__"
"    await self.app(scope, receive, sender)"
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py"", line 21, in __call__"
    raise e
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py"", line 18, in __call__"
"    await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/routing.py"", line 706, in __call__"
"    await route.handle(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/routing.py"", line 443, in handle"
"    await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/applications.py"", line 270, in __call__"
"    await super().__call__(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/applications.py"", line 124, in __call__"
"    await self.middleware_stack(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py"", line 184, in __call__"
    raise exc
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py"", line 162, in __call__"
"    await self.app(scope, receive, _send)"
"  File ""/usr/local/lib/python3.9/site-packages/brotli_asgi/__init__.py"", line 85, in __call__"
"    await responder(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py"", line 44, in __call__"
"    await self.app(scope, receive, self.send_with_gzip)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py"", line 84, in __call__"
"    await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py"", line 79, in __call__"
    raise exc
"  File ""/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py"", line 68, in __call__"
"    await self.app(scope, receive, sender)"
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py"", line 21, in __call__"
    raise e
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py"", line 18, in __call__"
"    await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/routing.py"", line 706, in __call__"
"    await route.handle(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/routing.py"", line 276, in handle"
"    await self.app(scope, receive, send)"
"  File ""/usr/local/lib/python3.9/site-packages/starlette/routing.py"", line 66, in app"
    response = await func(request)
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/routing.py"", line 235, in app"
    raw_response = await run_endpoint_function(
"  File ""/usr/local/lib/python3.9/site-packages/fastapi/routing.py"", line 161, in run_endpoint_function"
    return await dependant.call(**values)
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/apis/v0/handlers/info.py"", line 36, in api_info"
    return ApiInfo.parse_obj(service.api_status())
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/services/info.py"", line 92, in api_status"
"    elasticsearch=self._elasticsearch_info(),"
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/services/info.py"", line 98, in _elasticsearch_info"
    return self.__es__.client.get_cluster_info()
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/client_adapters/opensearch.py"", line 167, in get_cluster_info"
    return self.__client__.info()
"  File ""/usr/local/lib/python3.9/site-packages/argilla/server/daos/backend/base.py"", line 103, in __exit__"
    raise IndexNotFoundError(ex)
"argilla.server.daos.backend.base.IndexNotFoundError: NotFoundError(404, '')"
```

**Comment by frascuchon** [comment]
Hi @mnschmit it's normal since the latest docker image is not built. Some tests are failing in the CI pipeline. Let me review the errors.

**Comment by frascuchon** [comment]
I've done some tests to verify the `/api/_info` won't call the es backend. Please try pulling the docker image with the tag `feat-allow-pass-extra-config-to-search-backend-client`

**Comment by mnschmit** [comment]
Great, thank you for your quick reply @frascuchon !
With the tag `feat-allow-pass-extra-config-to-search-backend-client`, the error goes away :tada: 

Unfortunately, I have a new one...

`rg.init` works like charm. So I went ahead and tried to call `configure_dataset_settings` to create a new empty dataset. Here I get `400 true refresh policy is not supported`. The problem seems to be with [this line](https://github.com/argilla-io/argilla/blob/c5578356bcf782fd3fd10c56934897e9864271b6/src/argilla/server/daos/backend/client_adapters/opensearch.py#L599). If set to `True`, this makes the new index available to search at once, and that doesn't seem to be supported. I couldn't really find anything specific to how fast AWS OpenSearch serverless refreshes the indices, but the default in "normal" OpenSearch seems to be 1 second. So it might be ok to just not set `True` here and leave the default `False`, but if you had good reasons to set `refresh=True` here, I'd be fine if it was just configurable somehow. Maybe it could also be in the `argilla.server.settings`, which I anyway have to touch to set the `opensearch_extra_args`?

**Comment by mnschmit** [comment]
Hi @frascuchon ! Did you have time to think about the two options (at least I can see two; maybe there are others I didn't think of)?
I'll be on vacation starting next week. So if I can help before that, just let me know!

**Comment by frascuchon** [comment]
Hi @mnschmit Sorry for the late response. I'm a bit busy these days.

It looks like the OpenSearch serverless version is not fully compatible with the current Argilla implementation and a bunch of tests must be applied to sure the whole functionality. Unfortunately, this is not in our low-term roadmap and is something that we cannot tackle right now. 

But I encourage you to fork this branch and try to find a way to make it work with the serverless version. I will be happy to help you in the process if you finally decide to work on that. We can discuss through Slack about this if you prefer.

Thanks for all your feedback and sorry for not being more help

**Comment by mnschmit** [comment]
Thanks for the honest answer @frascuchon !
I think I'll get back to that after my vacation. I'll be happy to try a few things then, but I'll probably also need help with building the docker image to try it out in my AWS environment. A couple of faster iterations might take this issue a long way already. At least let's hope so ^^

I'll contact you (and maybe @davidberenstein1957) on Slack for more information on how to best try things out using docker when I'm ready to start :+1:

**Comment by mnschmit** [comment]
@frascuchon @davidberenstein1957 @gabrielmbmb 

Thanks again, all of you, for your help in this!
I got it to work with the serverless service now (but only barely). The main issue is that AWS Opensearch serverless does not support the refresh API. So we cannot enforce a refresh when indexing/updating/deleting a document, and neither can we wait for a refresh. Refreshes can happen in intervals between 10 and 60 seconds. So I tried to include a manual `time.sleep` after each request. This made all the errors go away, but also unnecessarily slowed down everything.
I have raised the issue with the AWS solution architect who is responsible for our company and maybe at some point they will find a better solution, but at the moment I abandon the serverless option and will stick to clusters.

It would still be great if the PR could be merged because the authentication part works like a charm and would still be useful for more secure authentication to the AWS cluster.

**Comment by frascuchon** [comment]
This PR won't be merged at the moment. We need to review all the server settings and provide a unified way to set up them from configuration files. (`config.ini`)

See https://github.com/argilla-io/argilla/issues/4219

**Comment by mnschmit** [comment]
Thanks, @frascuchon 
That makes sense to move server configuration to configuration files.

**Pull request closed without merging**
