### PR TITLE
Updating develop branch with changes from main

### PR DESCRIPTION
**Pull request by jfcalvo**
# Description

On the process to create a new release we start merging changes from `main` branch into `develop`.

Doing that for release 1.20.0 I have found many docs conflicts between main and develop so I'm open a PR to make the process more clear and avoid possible mistakes solving those conflicts from my side.

Once the conflicts are solved please can you check that your contributions are fine so I can merge the PR?

### CODE REVIEW

**Review by sdiazlor — COMMENTED** [review]
From my side, it seems to be fine

**Review by ignacioct — APPROVED** [review]
LGTM

**Comment by davidberenstein1957** [comment]
@ignacioct @sdiazlor, sadly there are some merge conflicts. Feel free to have a look together to include the relevant changes we made in `main` and align them with `develop`.

**Comment by sdiazlor** [comment]
> @ignacioct @sdiazlor, sadly there are some merge conflicts. Feel free to have a look together to include the relevant changes we made in `main` and align them with `develop`.

Yeah, I misunderstood what he was refering,  @kursathalat and me tackled this now

**Pull request merged**
