### PR TITLE
docs: blog post improving retrieval and reranking for RAG

### LINKED ISSUE #3896: [DOCS] Fine-tuning bi and cross encoder for RAG using the Argilla Trainer blogpost
## Which page or section is this issue related to?

The main idea is to write a blog post about using the Argilla Trainer to fine-tune bi- or cross-encoder for RAG.

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description
We added the blog post on fine-tuning the sentence similarity model for RAG

Closes #3896 

**Type of change**

(Remember to title the PR according to the type of change)

- [X] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [X] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [X] I added relevant documentation
- [X] I followed the style guidelines of this project
- [X] I did a self-review of my code
- [X] I made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, looking good already. I have some starting comments.

- Would you be able to align your approach with the `FeedbackDataset.for_sentence_similarity` or `FeedbackDataset.for_retrieval_augmented_generation` https://github.com/argilla-io/argilla/pull/3833? 
- The images don't seem to be working.
- I think you can go a bit more in-depth into retrieving the data from a vector search index. Something like [deepset ](https://haystack.deepset.ai/tutorials/07_rag_generator) can be used.

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, the tutorial is looking great already. How are you going to close the loop of retrieving documents and optimizing / labelling which are more similar based on the rag retrieval efforts? I think we need two datasets: one to assess the similarity of the sentences compared to the query and one to assess the similarity between sentences.

**Comment by sdiazlor** [comment]
@davidberenstein1957 I made some changes according to what we discussed

**Comment by davidberenstein1957** [comment]
Thanks @sdiazlor, you can walk us through them during the daily :)

**Comment by sdiazlor** [comment]
@davidberenstein1957 I made some changes but I have some comments on issue #4088 .

**Comment by sdiazlor** [comment]
Issue created for that #4088

**Comment by davidberenstein1957** [comment]
Hi @sdiazlor, could you align this with the most recent update from Agus w.r.t. changing the `RankingQuestion` to the `RatingQuestion`? Also, I think we need to update the images to align with the actual look of the datasets within the UI.

**Comment by sdiazlor** [comment]
> Hi @sdiazlor, could you align this with the most recent update from Agus w.r.t. changing the `RankingQuestion` to the `RatingQuestion`? Also, I think we need to update the images to align with the actual look of the datasets within the UI.

@davidberenstein1957 the ratingquestion has already been updated in the latest commit, the images are what are remaining due to the frontend problem I was having

**Comment by davidberenstein1957** [comment]
@sdiazlor, is this ready to merge?

**Comment by sdiazlor** [comment]
@davidberenstein1957 yes, we can merge it in develop as you mentioned

**Pull request merged**
