### PR TITLE
docs: use deadlinkchecker to correct for wrong urls [new changes]

### LINKED ISSUE #3836: [DOCS] use deadlinkchecker to correct for wrong URLs
## Which page or section is this issue related to?
https://www.deadlinkchecker.com/website-dead-link-checker.asp

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

Dead links were checked and changed. Most of the modified files are .md or .ipynb (images). Regarding the .py files, the same error link was changed, so they are updated in the corresponding .rst files.

Closes #3836 

**Type of change**

(Remember to title the PR according to the type of change)

- [X] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [X] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [X] I added relevant documentation
- [X] I followed the style guidelines of this project
- [X] I did a self-review of my code
- [X] I made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@sdiazlor looking good, but I think we want to refer our query HTMLs to this page https://docs.argilla.io/en/latest/practical_guides/filter_dataset.html. Something like `/practical_guides/filter_dataset` should work.

**Comment by sdiazlor** [comment]
> @sdiazlor looking good, but I think we want to refer our query HTMLs to this page https://docs.argilla.io/en/latest/practical_guides/filter_dataset.html. Something like `/practical_guides/filter_dataset` should work.

@davidberenstein1957 I found that URL in other existing notebooks, so do you refer to the page you mention in these cases too? The search bar in Argilla is driven by Elasticsearch's powerful [query string syntax](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-query-string-query.html#query-string-syntax).

**Comment by davidberenstein1957** [comment]
`/practical_guides/filter_dataset` also contains the query search syntax which is a little bit different from the elastic one.

**Review by davidberenstein1957 — COMMENTED** [review]
Hi @sdiazlor, this looks good but the Docstring referenced to `/practical_guides/filter_dataset` need to be  `https://argilla.readthedocs.io/en/stable//practical_guides/filter_dataset.html` because they will not work otherwise

**Comment by sdiazlor** [comment]
> Hi @sdiazlor, this looks good but the Docstring referenced to `/practical_guides/filter_dataset` need to be `https://argilla.readthedocs.io/en/stable//practical_guides/filter_dataset.html` because they will not work otherwise

@davidberenstein1957 if you go to the readthedocs link with the right URL is not working either.  Would https://docs.argilla.io/en/latest/practical_guides/filter_dataset.html work instead?

**Comment by davidberenstein1957** [comment]
Yes that is the correct one. @sdiazlor

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
