### PR TITLE
Add initial version of `deploy_on_spaces`

### LINKED ISSUE #5108: [FEATURE] add method to deploy on spaces through `huggingface_hub`
**Is your feature request related to a problem? Please describe.**
Argilla is cool but sometimes deployment can contain a lot of clickety steps with copy_pasting.

**Describe the solution you'd like**
Some underlying code that goes over steps on https://huggingface.co/docs/hub/en/spaces-sdks-docker-argilla but through the `huggingface_hub`SDK. 
https://huggingface.co/docs/huggingface_hub/main/en/guides/manage-spaces#manage-your-space

Also, the client might easily be initialized with the HF key headers after.

```python
rg.deploy_on_spaces(
    repo_id="user/name",
    private=True,
    admin_username=...,
    admin_password=...,
    admin_apikey=...,
) 
```

show a message:

```
Argilla has been deployed on a private HF Space with url http://hf.co/spaces/user/name. You can now connect with 
Client(etc)
```
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by davidberenstein1957**
# Pull Request Template

Add default deployment options for Hugging Face spaces through the Hugging Face hub api.

Closes #5108

- Added `DeploymentMixin` class within `_deploy.py` within `_helpers` directory
- Added `huggingface_hub` as core dependency under the assumption it is lightweight and we will soon use it for telemetry too.

TODO:
- docs
- tests
- evaluation w.r.t. oauth deployment for using `argilla` vs `argilla-space-with-oauth` @frascuchon do you know what the difference is when using these templates?

Usage:

```python
import argilla as rg

client = rg.Argilla.deploy_on_spaces(
    repo_id="my-org/my-space",
    token="hf_ABC123",
    space_storage="10GB",
    space_hardware="gpu",
    private=True,
    admin_username="admin",
    admin_password="password123",
    owner_username="owner",
    owner_password="ownerpass",
    annotator_username="annotator",
    annotator_password="annotatorpass",
    argilla_workspace="workspace",
    oauth_huggingface_client_id="client_id",
    oauth_huggingface_client_secret="client_secret"
)
```

**Type of change**

- New feature (non-breaking change which adds functionality)

**How Has This Been Tested**

**Checklist**

- I added relevant documentation
- follows the style guidelines of this project
- I did a self-review of my code
- I made corresponding changes to the documentation
- I confirm My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

**Review by burtenshaw — COMMENTED** [review]
This is useful functionality, but I'm not sure that it needs to be in the sdk because it will introduce maintenance challenges. As you mention in the comment: oauth, testing. 

Instead, could this be an example of the first extension?

**Comment by Josephrp** [comment]
it would fit quite nicely in a "huggingface spaces sdk" , which is something to look forward to

**Comment by davidberenstein1957** [comment]
@burtenshaw not sure why the OAuth is an issue. I thought of adding it as an extra but I think the value of the integration also lies in the fact that it works on the fly as an entry point so I would then propose showing it on import or function execution instead of mentioning it everywhere through the docs. WDYT?

**Comment by davidberenstein1957** [comment]
@frascuchon `argilla-space` vs `argilla-space-with-oauth` do you know what the difference is between these Hugging Face spaces templates?

**Comment by burtenshaw** [comment]
> @burtenshaw not sure why the OAuth is an issue. I thought of adding it as an extra but I think the value of the integration also lies in the fact that it works on the fly as an entry point so I would then propose showing it on import or function execution instead of mentioning it everywhere through the docs. WDYT? 

Sorry. I didn't explain this point properly. I meant that oauth, and other challenges, could increase the complexity of the module and so might be better placed in another package.

That said, I'm not 100% against this inclusion in the SDK. But I do think it's a significant change that we should find the best place for. My main concern is that we end up with too much utilities code in the SDK that's difficult to maintain on a daily basis. And doesn't offer much value to the user beyond a well documented Spaces deployment guide.

If we do include this in the SDK, rather than an extension, I'd say that we should interface it consistently with the `Argilla` class.

But, I'd like to also here from @frascuchon and @dvsrepo .

**Comment by burtenshaw** [comment]
> it would fit quite nicely in a "huggingface spaces sdk" , which is something to look forward to

@Josephrp what's the latest on this?
@davidberenstein1957 should we follow this up?

**Comment by dvsrepo** [comment]
> @frascuchon `argilla-space` vs `argilla-space-with-oauth` do you know what the difference is between these Hugging Face spaces templates?

The official is this one: https://huggingface.co/spaces/argilla/argilla-template-space (the one that is used by the New Space UI HF flow too).

The other one is an unofficial one I created to be able to launch oauth spaces more easily

**Comment by davidberenstein1957** [comment]
@dvsrepo @burtenshaw and I decided to go forward with this. @frascuchon do you have any specific opinion about the PR and location of the `Mixin` within the package?

**Comment by nataliaElv** [comment]
@davidberenstein1957 Is this ready to go into `2.1.0` version or should I move it to `2.2.0`?

**Pull request closed without merging**
