### PR TITLE
bug: FloatMetadataProperty: value is not a valid float when it is an rounded integer

### LINKED ISSUE #4570: [BUG-python] `FloatMetadataProperty`: value is not a valid `float` when it is an rounded integer
**Describe the bug**
Using `distilabel` and `to_argilla` method raises this error regarding metadata and `text-descriptives`.

```bash
ValueError: `FeedbackRecord.metadata` {'length-input': 19, 'length-instructions': 106, 'generation-model': 
'gpt-3.5-turbo', 'input_n_tokens': 2, 'input_n_unique_tokens': 2, 'input_n_sentences': 1, 'input_perplexity': 1, 
'input_entropy': 0, 'input_flesch_reading_ease': -48.99, 'instructions_n_tokens': 18, 
'instructions_n_unique_tokens': 18, 'instructions_n_sentences': 1, 'instructions_perplexity': 1.79, 
'instructions_entropy': 0.58, 'instructions_flesch_reading_ease': 61.67} does not match the expected schema, with 
exception: 2 validation errors for MetadataSchema
input_perplexity
  value is not a valid float (type=type_error.float)
input_entropy
  value is not a valid float (type=type_error.float)
```

**Expected behavior**
I would expect this check to pass given that any integer is a rounded of float.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.23
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 

**Additional context**

### PR DESCRIPTION
**Pull request by sdiazlor**
# Description

With the removal of this line,  x.0 values will not be rounded so that it passes the FloatMetadataProperty validation. The error comes from the initial definition of the metadata property as float, but then casting and adding as value an integer.

NOTE: This fixes the bug error directly, although this question is still pending @alvarobartt:
>However, from a usability perspective there is also the issue of not allowing for passing a rounded float like 1.0 to an IntegerMetadataProperty and perhaps also not an integer like1 to a FloatMetadataProperty.

Closes #4570 

**Type of change**

(Please delete options that are not relevant. Remember to title the PR according to the type of change)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes. And ideally, reference `tests`)

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [x] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by alvarobartt** [comment]
Hi here @sdiazlor, thanks for the PR! w.r.t. @davidberenstein1957's question, I'm not sure, because if we have an `IntegerMetadataProperty` we should enforce the values to be `int`, not casting those to `int` i.e. `1.0 -> 1`; same thing for the `FloatMetadataProperty`, which shouldn't cast to `float` by default. So IMO we can keep the casting within the `text-descriptives` integration while keeping `argilla` as is, also what do @jfcalvo and @frascuchon think about that?

**Review by davidberenstein1957 — APPROVED** [review]
@sdiazlor could you also check if this work with the error Dani was experiencing?

**Comment by davidberenstein1957** [comment]
> Hi here @sdiazlor, thanks for the PR! w.r.t. @davidberenstein1957's question, I'm not sure, because if we have an `IntegerMetadataProperty` we should enforce the values to be `int`, not casting those to `int` i.e. `1.0 -> 1`; same thing for the `FloatMetadataProperty`, which shouldn't cast to `float` by default. So IMO we can keep the casting within the `text-descriptives` integration while keeping `argilla` as is, also what do @jfcalvo and @frascuchon think about that?

The proposed changed avoids the casting to `int` right? For me, it was more of a philosophical question about whether or not it made sense to allow for this, outside of this basic PR. I understand why but from a user experience it might be weird that it is impossible to add an `1.0` to an `IntegerMetadataProperty` or a `1` to a `FloatMetadataProperty`.

**Comment by sdiazlor** [comment]
> @sdiazlor could you also check if this work with the error Dani was experiencing?

@davidberenstein1957 Yes, I already did. And with a similar case (using to_argilla method), it didn't raise the validation issue. Below, you can see that the values are floats.
image

**Pull request merged**
