### PR TITLE
Release v1.7.0

### PR DESCRIPTION
**Pull request by frascuchon**
### Added

- add `max_retries` and `num_threads` parameters to `rg.log` to run data logging request concurrently with backoff retry policy. See [#2458](https://github.com/argilla-io/argilla/issues/2458) and [#2533](https://github.com/argilla-io/argilla/issues/2533)
- `rg.load` accepts `include_vectors` and `include_metrics` when loading data. Closes [#2398](https://github.com/argilla-io/argilla/issues/2398)
- Added `settings` param to `prepare_for_training` ([#2689](https://github.com/argilla-io/argilla/issues/2689))
- Added `prepare_for_training` for `openai` ([#2658](https://github.com/argilla-io/argilla/issues/2658))
- Added `ArgillaOpenAITrainer` ([#2659](https://github.com/argilla-io/argilla/issues/2659))
- Added `ArgillaSpanMarkerTrainer` for Named Entity Recognition ([#2693](https://github.com/argilla-io/argilla/pull/2693))
- Added `ArgillaTrainer` CLI support. Closes ([#2809](https://github.com/argilla-io/argilla/issues/2809))

### Changed

- Argilla quickstart image dependencies are externalized into `quickstart.requirements.txt`. See [#2666](https://github.com/argilla-io/argilla/pull/2666)
- bulk endpoints will upsert data when record `id` is present. Closes [#2535](https://github.com/argilla-io/argilla/issues/2535)
- moved from `click` to `typer` CLI support. Closes ([#2815](https://github.com/argilla-io/argilla/issues/2815))
- Argilla server docker image is built with PostgreSQL support. Closes [#2686](https://github.com/argilla-io/argilla/issues/2686)
- The `rg.log` computes all batches and raise an error for all failed batches.
- The default batch size for `rg.log` is now 100.

### Fixed

- `argilla.training` bugfixes and unification ([#2665](https://github.com/argilla-io/argilla/issues/2665))
- Resolved several small bugs in the `ArgillaTrainer`.

### Deprecated

- The `rg.log_async` function is deprecated and will be removed in next minor release.

### CODE REVIEW

**Comment by tomaarsen** [comment]
@davidberenstein1957 @frascuchon do we intend to include #2691 in 1.7.0?

**Comment by davidberenstein1957** [comment]
IMO yes. I also briefly discussed this but perhaps Paco missed this?On 2 May 2023, at 09:11, Tom Aarsen ***@***.***> wrote:﻿
@davidberenstein1957 @frascuchon do we intend to include #2691 in 1.7.0?

**Comment by frascuchon** [comment]
I've updated the release branch with the latest changes from develop branch. Please, @davidberenstein1957 @tomaarsen, take a look at PR description to confirm we've not missed anything

**Comment by tomaarsen** [comment]
Test failures are due to issues on HuggingFace's side, i.e. that the `sentence-transformers` models are unavailable: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

The relevant logs:
```
>               raise RepositoryNotFoundError(message, response) from e
E               huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6459e566-7f81ffa2104fbfa60ef25036)
E               
E               Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2.
E               Please make sure you specified the correct `repo_id` and `repo_type`.
E               If you are trying to access a private or gated repo, make sure you are authenticated.
E               Invalid username or password.
```

Tests should pass again once https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2 is back.

**Comment by davidberenstein1957** [comment]
The entire https://huggingface.co/sentence-transformers organisation is gone.

**Comment by tomaarsen** [comment]
https://twitter.com/huggingface/status/1655760648926642178?s=20

Their CSS was also broken earlier today, and right now `load_dataset` won't work, it'll run endlessly without ever loading the dataset.

**Pull request merged**
