### PR TITLE
docs: Updated developer documentation

### LINKED ISSUE #3964: [DOCS] update developer documentation on server/sdk
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/community/developer_docs.html
- work on server/sdk
    - install requirements
    - install code formatting tools
    - launch general elasticsearch docker
        
        https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker.html
        
    - do database migrations:
        - https://docs.argilla.io/en/latest/getting_started/installation/configurations/database_migrations.html#apply-the-latest-migration
    - create default user
        - python -m argilla server database create_default
    - launch local python server
        - `ARGILLA_ENABLE_TELEMETRY=0` python -m argilla server start
    - (Potentially) build UI
        - @Kursat Halat
    - add updates
    - run tests
        - pytests tests

### LINKED ISSUE #3977: [DOCS] clarify `CLI` login flow and user creation in docs
## Which page or section is this issue related to?
Vikas Mehta found it difficult to work with this and I agree with him.

### PR DESCRIPTION
**Pull request by kursathalat**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #3964 
Closes #3977 

**Type of change**

(Remember to title the PR according to the type of change)

- [x] Documentation update

**How Has This Been Tested**

(Please describe the tests that you ran to verify your changes.)

- [ ] `sphinx-autobuild` (read [Developer Documentation](https://docs.argilla.io/en/latest/community/developer_docs.html#building-the-documentation) for more details)

**Checklist**

- [x] I added relevant documentation
- [ ] I followed the style guidelines of this project
- [ ] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I filled out [the contributor form](https://tally.so/r/n9XrxK) (see text above)
- [ ] I have added relevant notes to the `CHANGELOG.md` file (See https://keepachangelog.com/)

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@kursathalat can you make your changes in `developer_docs.md`?

Also, your changes don't really follow the steps I highlighted in the issue yet. Could you try to follow those to make it a bit more clear then it currently is?

**Comment by davidberenstein1957** [comment]
Hi @kursathalat this is looking fine already. 
- I think you can add some more context to the general introduction. 
- Also, something like code formatting should come right after installing the environment. 
- Additionally, a basic instalment always requires the SDK and Elastic search.
- you left a section about troubleshooting the docs after running tests
- there is no comprehensive nesting of headers yet
- there is duplicate text about building the frontend, I would rather see a reference to associated section
- there are some wrong headers

I would expect something like this:
- Setup Python environment
    - Clone the Argilla repository
    - install dependencies
        - via pip
        - via conda
    -  install code formatting
- Setup Databases
    - Vector Database
    - Relational Database and migrations
- Setup frontend
    - build
    - run
- Setup the server
    - default user
- Make your contribution
    - contributor guides
    - (re)launch server with changes
    - run tests

**Comment by davidberenstein1957** [comment]
Hi @kursathalat, Looking much better now 💪🏽 Some minor nitpicks: I don't see any info w.r.t. re-launching the server during the testing phase. Also, you left a section about troubleshooting the docs after running tests, but this is irrelevant. Did you test and verify each of the steps and does it work for you when you follow them?

Maybe it makes sense to add this as introduction section instead of the current intro? https://docs.argilla.io/en/3964-docs-update-developer-documentation-on-serversdk/index.html#project-architecture

@sdiazlor, could you add some context about the using and running the documentation before I merge this. I think this can become a completely separate header.

**Comment by kursathalat** [comment]
> Hi @kursathalat, Looking much better now 💪🏽 Some minor nitpicks: I don't see any info w.r.t. re-launching the server during the testing phase. Also, you left a section about troubleshooting the docs after running tests, but this is irrelevant. Did you test and verify each of the steps and does it work for you when you follow them?
> 
> Maybe it makes sense to add this as introduction section instead of the current intro? https://docs.argilla.io/en/3964-docs-update-developer-documentation-on-serversdk/index.html#project-architecture
> 
> @sdiazlor, could you add some context about the using and running the documentation before I merge this. I think this can become a completely separate header.

What do you think about the intro? The command in the launch server section (thanks to @gabrielmbmb) just automatically updates the server after every change, so I did not include it there.

**Comment by sdiazlor** [comment]
> Hi @kursathalat, Looking much better now 💪🏽 Some minor nitpicks: I don't see any info w.r.t. re-launching the server during the testing phase. Also, you left a section about troubleshooting the docs after running tests, but this is irrelevant. Did you test and verify each of the steps and does it work for you when you follow them?
> 
> Maybe it makes sense to add this as introduction section instead of the current intro? https://docs.argilla.io/en/3964-docs-update-developer-documentation-on-serversdk/index.html#project-architecture
> 
> @sdiazlor, could you add some context about the using and running the documentation before I merge this. I think this can become a completely separate header.

Yes, I'll add it, I was waiting for Kursat to finish to avoid disagreements in the branch

**Comment by sdiazlor** [comment]
@davidberenstein1957 do you think this way is more complete?

**Comment by davidberenstein1957** [comment]
Handles this issue too: https://github.com/argilla-io/argilla/issues/3977

**Review by davidberenstein1957 — APPROVED** [review]

**Pull request merged**
