### PR TITLE
[Docs] Add WeaSEL example to weak supervision guide

### LINKED ISSUE #565: [Labeling] Include a weasel example to the labeling guide

### PR DESCRIPTION
**Pull request by dcfidalgo**
@dvsrepo This would be an example of how to use weasel with an HF transformers model. Maybe we can discuss this next week.

https://github.com/recognai/rubrix/blob/c585b4524d457cc5da44b1126487f39f18a38014/docs/guides/weasel.ipynb

closes #565

### CODE REVIEW

**Comment by dvsrepo** [comment]
Wow!

**Comment by dcfidalgo** [comment]
#565

**Comment by dcfidalgo** [comment]
Ok, I added the WeaSEL example to the supervision guide. I also fixed a bug in the guide (not related to weasel) that I introduced the last time ... Closes #565 
@dvsrepo You can have a look at the example here: https://github.com/recognai/rubrix/blob/076fbdfa98a192a5ef92c768ca9e3e8d2a399975/docs/guides/weak-supervision.ipynb

**Review by dvsrepo — APPROVED** [review]
This is beautiful David 💌

**Pull request merged**
